src/tcgwars/logic/impl/gen1/BaseSet.groovy, src/tcgwars/logic/impl/gen7/BurningShadows.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/DragonMajesty.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/GuardiansRising.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy
Added sources to many trainers and abilities. This is meant to address bugs where effects like Safeguard or preventAllEffectsNextTurn stop trainers and abilities from targeting them. Adding sources prevents them from being categorized as effects from attacks.
=> Trainer fixes

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
This PR introduces the first implementation for the Pokemon Unified Minds set.
There are about 162 Pokemon Cards being implemented with their abilities and moves.  There are 13 moves/abilities that have not been written yet because they need require further discussion on how best to complete them.  
This needs to be tested on the dev server.
=> Implement unified minds pokemon

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
These are the initial fixes that were found for the cards 1-60
This includes:
- Leavanny's Blanket weaver correctly reduces grass attack damage 
- Lapra's Mermaid Call should refer to Misty's Favor and not Misty's Request
- Improve wording on Froslass's Spiteful Sigh
- Basculin's Swarming Bites should not crash game
- Araquanid's Sticky Web should not crash game
- Tapu Fini's attack should not crash game
- Raichu Alolan Raichu Gx's Lightning Ride GX should not crash game
=> Unified Minds Fixes

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
This PR includes more fixes to the list of initial issues for the UNM set implementation.
The fixes include: 
- Fix TORNADUS_178 Thunderous Tornado
- Fix BASCULIN_43 Swarming Bites
- Add fix for GIRATINA_86 Dimensional Breach
- Fix MELOETTA_123 Tag Cheer
- Fix KANGASKHAN_163 Tag Impact
- Fix KOMALA_185 Snooze and Drowsing
- Fix UMBREON_DARKRAI_GX_125 Black Lance and Dark Moon GX
- Fix MEGA_SABLEYE_TYRANITAR_GX_126 Greedy Crush and Gigafall GX
=> More Unified Mind Bugfixes

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
This PR includes another set of fixes for a the list of issues in the initial implementation of UNM.
The fixes include:
- Fix DRAGONITE_GX_152 Mach Delivery GX
- Fix COACH_TRAINER_192
- Fix GREAT_POTION_198
- Fix BLIZZARD_TOWN_187
- Fix UMBREON_DARKRAI_GX_125 Black Lance
- Fix ROWLET_ALOLAN_EXEGGUTOR_GX_1 Tropical Hour GX
- Fix CHANDELURE_30 Spirit Burner
- Fix VICTINI_26 Victory Sign
- Edit NAGANADEL_GX_160's Ultra Conversion ability to have different different dialog text
- Fix GUMSHOOS_181 Alert Headbutt
- Fix SLAKING_170 Dynamic Swing
=> Unified Mind Fixes

src/tcgwars/logic/impl/gen8/SwordShield.groovy
excluded itself from list of available cards to discard for the effect so quick ball can't discard itself for search on play
=> quick ball fix

src/tcgwars/logic/impl/gen8/SwordShield.groovy
The text was implying the same effect as Nest Ball, when it isn't actually that effect
=> Fix QUICK_BALL_179's text

src/tcgwars/logic/impl/gen7/CelestialStorm.groovy
Incorrect name of the card lets you put 4 of the normal art and 4 of the full art since they have different names
=> Fix STEVENS_RESOLVE_145

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
It was always confusing that it said "Paranormal" prevented the damage when there is nothing on Latios GX's card called this. It should've been Tag Purge
=> Change wording on LATIOS_GX_78's attack

src/tcgwars/logic/impl/gen7/ShinyVault.groovy
The older cards will need marked as excluded in standard (slightly big task but I can knock it out), but I don't see any reason this would be difficult to throw on in. Would be a nice thing to help compliment since we already have the scans and DB info.
=> Implement Shiny Vault

src/tcgwars/logic/impl/gen8/RebelClash.groovy
Adaptive evolution allows catterpie and metapod to evolve on both the player’s first turn and on the turn it was put into play. The previous implementation only allowed them to evolve on the first turn if the player went second.
=> Fixed caterpie_1 and Metapod_2 Adaptive Evolution

src/tcgwars/logic/impl/gen8/RebelClash.groovy
I misclicked it while testing and though something as impactful as shuffling a pokemon into its owners deck would benefit from a confirmation
=> Added a confirm to flapple_22 ability

src/tcgwars/logic/impl/gen8/RebelClash.groovy
Unsure if I'm reading correctly, but I think this is the change that needs done. It's either this or it just needs to be "flip" and not "flip 1,"
[Build error for reference](https://dev-ci.tcgone.net/logs?sha=61d592eac1c87ed9b52267b557e8c4b322118b68)
=> Fix build due to "flip" on Perish Body

src/tcgwars/logic/impl/gen8/RebelClash.groovy
Your opponent only switches their active pokemon with one of their benched pokemon if you do first.
=> Changed Bronzong_130s Gyro ball

src/tcgwars/logic/impl/gen8/RebelClash.groovy
now it prevents damage after w/r and from any of the opponent’s defending pokemon
=> fixed electivire indent and zamzenta guard press

src/tcgwars/logic/impl/gen8/RebelClash.groovy
They no longer provide energy while not attached to a pokemon
=> Changed Horror psychic and speed lightning

src/tcgwars/logic/impl/gen7/DetectivePikachu.groovy
Mr.Mime now moves the prize card to the top of the deck rather than cloning it there.
=> Mr.Mime fix

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Heatran’s ability currently activates when the opponent’s pokemon is knocked out and the select a new active at the beginning of the next turn. If this works I wll copy it to xernias prism star and cinderace
=> Heatran ability fix

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
For future reference on SWITCH the targets are ef.switchedOut and ef.fallenBack I dont know where to look for these names other than by searching through previously implemented cards.
=> Heatran ability take 2

src/tcgwars/logic/impl/gen4/Unleashed.groovy
https://forum.tcgone.net/t/br-kingdra-ul-85-dragon-steam-is-currently-coded-to-cost-a-w/9707?u=mt.gufo
=> Fixed Kingdra’s attack cost

src/tcgwars/logic/impl/gen8/RebelClash.groovy
No longer checks top pokemon when not attached to a pokemon
=> Fix twin energy

src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
https://forum.tcgone.net/t/br-pawniard-cec-134-used-bag-slash-while-opponent-had-no-ite/9717?u=mt.gufo
=> FIxed Pawniard’s attack

src/tcgwars/logic/impl/gen8/RebelClash.groovy
Falinks V no longer decreases damage to your opponents’ falinks
https://forum.tcgone.net/t/br-falinks-v-rcl-110-the-ability-should-not-affect-both-side/9719?u=mt.gufo
=> Falinks V ability fix

src/tcgwars/logic/impl/gen8/RebelClash.groovy
Code stolen from pokeflute from gen 1
If this doesn’t work ill put the card on the opponent’s bench
=> Fixed top entry benching on the opponent’s bench

src/tcgwars/logic/impl/gen8/RebelClash.groovy
Nugget now properly discards itsself when played and doesn’t chain
=> Nugget fixes

src/tcgwars/logic/impl/gen8/RebelClash.groovy
I think getters cant get attacks from pokemon that dont belong to the active player? The previous attempt correctly added C to the defending pokemon’s attack cost but when Nine Temptations copied it.
=> Reverted Ninetales V

src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
Not sure why the build broke? ef as TargetedEffect has worked before.
=> Jolteon GX

src/tcgwars/logic/impl/gen7/LostThunder.groovy
Effect shouldn’t unregister when ariados is switched or evolved. 
https://forum.tcgone.net/t/br-switch-cls-147-ariados-lot-10-switch-was-used-despite/9779/2?u=mt.gufo
=> ariados_10

src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
The effect works as intended including ttgx costs. It can even be copied by copying attacks properly.
=> Final Sunflora

src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
No longer prevents nondamage effects of attacks done to other pokemon
=> Cosmog_100

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Since the first damage counter is required the loop should only loo through twice
=> Grimsley loop fixed

src/tcgwars/logic/impl/gen3/UnseenForces.groovy
snappy move can only be used once per turn
=> aipom ability

src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
The ability didn’t function if a pokemon was knocked out on the opponent’s previous turn and then another one was knocked out by between turns effects.
=> Oricorio Gx ability

src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
it.EX is for pokemon ex it.POKEMON_EX is for pokemon EX. Dont you love the naming conventions?
=> Altaria EX check fix

src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
Shuffles deck even if no new deoxys is chosen
=> Deoxys_3 tweak

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Same idea as #208 like last time. Comment if you believe anything I put is redundant, grammatically incorrect, or has a syntax error.
Cleans up some redundant spacing on internal attack texts. Also adds the following that is unrelated to the clearup:
* MUNCHLAX_173 now has a confirm dialog to use Snack Search. (thanks for your help Lithogen!)
* DRUDDIGON_157's Drag Off was fixed to only work if the opponent had Pokemon on the bench.
* RELICANTH_111's Deep Sea Boring no longer shows the opponent the selected Trainer.
* GIANT_HEARTH_197 no longer shows the selected Fire Energy to the opponent.
=> Unified Minds clearup/cleanup/minor fixes

src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy
Fixed target checking and removed active gx check since non gx pokemon can copy gx attacks.
=> Celesteela GX fix

src/tcgwars/logic/impl/gen3/LegendMaker.groovy
Trello bug report was incomplete, the direct damage was correct but I was confused because regular damage was happening also. There is no regular damage printed on the card so it was removed.
=> Fix Registeel Star

src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
It was a comma... I rewrote this from scratch to find out you did it correctly the first time and missed a comma. Feels bad man but nice job!
=>  Combusken fix

src/tcgwars/logic/impl/gen3/UnseenForces.groovy
I think select parameters are different for card lists and pokemon lists.
=> Fixed espeon ex

src/tcgwars/logic/impl/gen7/TeamUp.groovy
Removed deck as attack requirement and now only searches lightning energy if you have a deck
=> Fix Pikarom TEU 33

src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
Previous implementation blocked trainer cards
=> Properly unregister’s jolteon’s effect.

src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy
Reverted changes as they allowed pokemon to break holon circle without having the energy to attack. Testing different timing on changing phase vs preventing effects. Added preventing attack damage as previous versions did not.
=> Holon Circle

src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
Alas twas not meant to be. But at least it wasn’t just GL that had bugs. Changed all holon energys to only check for basic energys of the required type. Added an EX check to the w portion of holon energy wp, and added more cases to remove special conditions with GL.
=> Holon energy fixes

src/tcgwars/logic/impl/gen7/UltraPrism.groovy
Should allow the player to choose the order the cards are placed on the bottom of the deck as the attack states.
=> Fix Oranguru UPR-114 Resource Managment card order

src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
Since play from hand check crashes the game im just going to hope that EVOLVE_STANDARD requires play from hand.
=> Kabutops 10

src/tcgwars/logic/impl/gen3/UnseenForces.groovy
This was annoying to do without find/replace.
=> Unown shuffle pokepower can only be used once per turn

src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
hmmm why is type acting differently than mew*?
=> Holon Tower

src/tcgwars/logic/impl/gen3/PowerKeepers.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy
uses the pokemon type instead of the type of the top card
=> Fix type finding

src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
Cards are still considered basic after discard. Attempt to revert the changes with a delayed effect on the affected card being removed from play.
=> Mark as basic - card still considered basic after discard

src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
I'm pretty sure I'm trying to add a `onRemoveFromPlay` closure directly to the card similar to how I'm directly manipulating the `cardTypes`. This is feeling more wrong the further I go down this rabbit hole, but I'm still curious if it works.
=> Mark as basic - a different approach to not staying basic when removed from play

src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
Another shot at this. I don’t understand why it’s failing. My current guess has to do with the way im storing the objects but im not sure. Method works fine for vaporeon_42 from cosmic eclipse
=> Holon Veil

src/tcgwars/logic/util/PokemonCardSet.java
If this works as I intend, whenever a card would normally use .cardTypes.is(DELTA) instead it would call the created method and if ampheros delta is in play it would return true. I have very little understanding of how things work outside of implementation so I would greatly appreciate it if @axpendix could look it over and/or tell me what I did obviously wrong.
=> Added method isPokemonDelta

src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
This reverts the changes I've made so far. According to @axpendix this is not the correct way to go about having the Pokemon cards put into play by these effects be considered a Basic Pokemon. Apparently, a Pokemon card in play without another card under it should already be considered basic. However, the way other cards check if a Pokemon card is basic doesn't seem to line up with this. I'm going to need to figure out what the best way to handle this actually is.
=> Mark as basic

src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy
This is the same way other instances of evolutionary advantage handle
this. This allows you to evolve to Floette on the same turn you play
Flabebe, solving
https://forum.tcgone.net/t/br-flabebe-fli-83-flabebes-evolutionary-advantage-ability-d/9916
Relevant ruling:
Evolutionary Advantage    (Shinx - Ultra Prism)
>    Q. Does Shinx have to be in play at the beginning of the turn in
order to use its "Evolutionary Advantage" Ability?
A. It doesn't matter whether it was already in play or not, as long
as it's during "the first turn of the person going second".
(Ultra Prism FAQ; Feb 1, 2018 TPCi Rules Team)
=> Flabebe 83 Add missing args

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Perfection adds the moves rather than letting you select a move to use. This should allow cost altering effects work properly with perfection.
=> Perfection cost bugfix

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Didn’t work. I don’t know any other way to compare moves within lists that would work as moves with the same name can have different effects.
=> Revert "Optimized Perfection"

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Maybe by storing the actual card I can prevent duplicates. Probably breaks down if someone uses multiple versions of cards in their deck but who does that?
=> Testing list holding topPokemonCard

src/tcgwars/logic/impl/gen7/CelestialStorm.groovy
It should only prevent effects to the benched pokemon of the opponent of the attacker.
=> Sky Pillar

src/tcgwars/logic/impl/gen8/RebelClash.groovy
Prankish should not be limited to only once per turn. It should trigger
every time the Clefable is played from the hand to evolve a Pokemon.
This should fix
https://forum.tcgone.net/t/br-clefable-rcl-75-you-should-be-able-to-use-more-than-one-p/9930
Note: The text attribute for the ability states "Once during your turn," but [the actual card does not](https://tcgone.net/cards/clefable-rcl-75). Should this be corrected as well?
=> Clefable 74 RCL - Prankish not only once per turn

src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen8/SwordShieldPromos.groovy
Fixes
* Alolan Marowak (CIN 12) now counts energy attached to all of the opponent's Pokémon, not only the Active one.
* Two typos on SM Promo cards.
* Added a missing warning on Murkrow (UPR)'s attack.
* Removed an outdated typo on Gyarados-GX (CIN).
=> Polteageist V (SWSH21)'s Ability; plus some minor fixes on SMP, UPR and CIN

src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
The effect works correctly but a visual indicator is needed. I can’t think of any way to indicate to an opponent which pokemon got the counter, especially if they have 2 identical pokemon.
=> Tyranitar ex delta qol

src/tcgwars/logic/impl/gen8/RebelClash.groovy
I over-removed when fixing the ability. Without powerUsed the "used
ability" text doesn't seem to appear in the game log, which is certainly
problematic.
Whoops.
=> Clefable RCL 75 - Correct ability text in log

src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
The metronome code looked good so im guessing there was a missing import. It wasn’t obvious to me which import was missing so I included everything that was in pokemod that wasn’t in this as the same code works properly there.
=> Fix build maybe

src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/DragonMajesty.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Card fixes:
* Mew (UNB 76): Shouldn't block damage done from its own side.
* Mallow & Lana (CEC 198): Heal should happen after the switch, otherwise it won't be blocked by some cards (e.g. Lunala GX's "Moongeist Beam").
* Switch Raft (DM 62): should heal only if the pokemon switched.
Minor changes:
* DE/EM/TRR: replaced some hardcoded assets with `checkNoSPC()`.
* LM: removed unnecesary `def`.
* UNM: removed unnecesary `assert`.
* LOT/SMP/TEU: replaced "is" for "are" in some warnings.
=> Multiple card fixes

src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
Electivire specifically will need testing, see if the Poké-Power works consistently.
Fixes:
* Missing `def` on Lopunny (10) 
* Lopunny (10) now does bench damage on Flop.
* Medicham (32) now puts damage counters on bench instead of plain damage.
* Munchlax (33) gives a proper warning, and actually discards 2 cards before attacking.
* Noctowl (34) should now place the new prize facing up.
* Wobbuffet (35)... Hopefully this works, as of rn it ignored cards like Metal Goggles (TEU)
* Cascoon (44) throws an error when trying to give through [DEV], hoping this fixes it.
* Missing text on Grotle (49)
* Haunter (50) now does the "Defending Pokémon is Asleep" check on `attackRequirement`. Most attacks validate that way (and impede attacking for nothing), so switched it up.
=> More DP Fixes and Baby Check Implementation on 3, 18 & 37

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/GuardiansRising.groovy, src/tcgwars/logic/impl/gen7/SunMoon.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy
~~Drafted until figuring out a detail on Mallow & Lana.~~ **Ready to go!**
* Lunala-GX (SUM 66): Moongeist Beam's no heal effect should be removed on switch (Mallow & Lana, or Switch Raft should work here). **(Second Fix: Made Lunala use `cantBeHealed(defending)` and applied this fix there, should also fix Tentacool GRI 23)**
* Stoutland (SUM 50): Simplified "Ferocious Bellow" to  common method. Reason: The damage reduction is on the defending Pokémon, not on Stoutland. It shouldn't be unregistered after Stoutland switches out.
* Absol (GRI 81): Doom News shouldn't be unregistered if Absol switches out or evolves(?).
* Jirachi Prism Star (CES 97): Sams as Absol but with Perish Dream here.
* Frogadier (UNB 52): should lose the effect of AfterImage Strike if devolved.
=> Fixes related to Switching, Heal Blocking and Pokémon evolving

src/tcgwars/logic/impl/gen1/WizardsBlackStarPromosNG.groovy, src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen4/Unleashed.groovy
* WBSP: Lucky Stadium (41) should check for players having cards in their deck.
* FRLG: Onix (42) now checks for bench, and applies the restriction to attack next turn.
* DS: Potion (101) was pointing to the wrong card id.
* UL: Tropius' (66) "Green Call" didn't search for the proper amount of [G] Pokémon.
=> Some card fixes on WBSP, FRLG, DS and UL

src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
Feedback on how good/bad of an idea this might be would be appreciated.
Also not sure if a CardList can be set as persistent without a "name" attribute. Could I use the empoleon's UUID maybe? In case of a mirror match, so each "Out of Board" area has a separate identifier, even if not used.
=> Potential fix for Empoleon Lv. X (DP 120)

src/tcgwars/logic/impl/gen8/RebelClash.groovy
Forest Feast now correctly searches for Basic Grass Pokemon.
=> Rillaboom V - fixed first attack

src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
* Trying a new Budew (43) impl, see if it fixes Roselia (96) "devolving" on certain ocassions.
* Fixed a typo in Magneton (54) code.
* Silcoon (63) should impede from attacking, not from retreating.
* Unown C (67) should now assert having bench space before using CALL.
* Use select(), not choose() in Unown D (68) DRAW PPower.
* Bidoof (70) now asserts having items in the discard pile.
* Bonsly (71) now reduces the damage it takes next turn.
* Glameow (83) now reduces damage done by defending, not damage it takes from any attacker.
* Fixed a typo in Night Pokémon Center (108)
* Minor text fixes on Rival (113).
* Fix Attempt at Speed Stadium (114).
* Empoleon Lv.X (120) should not be able to attack the turn after using "Hydro Impact".
=> DP: Another round of general fixes.

src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy, src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy, src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen3/UnseenForces.groovy, src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
Main missing change for DP is implementing the Lv. X mechanic, but that needs help from the main devs no matter what 😅 
Changes done:
* Implemented "Leech Seed" on Cherubi (75)
* Removed a TODO on Noctowl (34)
* Added a `bc` after cards taken by Empoleon Lv. X (120) are given back.
* Implemented `checkCanBabyEvolve` and `babyEvolution` on all available EX era sets. Should work as before but simplified.
=> Final batch of fixes for DP basic use, and modularization of EX-era babies

src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen7/HiddenFates.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy
* Rocket's Admin (TRR 86): Players should draw at least 1 card, if possible to.
* Jolteon (HIF 23) should put 3 damage counters per attach, not 2.
* Purugly (UNB 160): Now discards the cards, instead of shuffling them into the deck.
* ~~Pyukumuku (UNB 53): Now uses rockPaperScissors instead of flip.~~ **Reverted while rethinking this implementation,**
* Hypno (DS 23) now switches instead of doing whirlwind.
* Slowking (DS 28)'s Prize Shift now asserts the player having hand.
* Wurmple (LM 70) now switches instead of doing whirlwind.
* Brock's Grit (TEU 135) now gives the correct warning for no elegible cards.
* Shuckle (RCL 5) should return at least a single basic energy card.
=> General Card Fixes

src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Prev result:
groovy.lang.MissingPropertyException: No such property: STAGE_1 for class: tcgwars.logic.groovy.TcgBuilders
[...]
(MysteriousTreasures.groovy:2448)
=> Fosil Excavator Part 2.1

src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen7/DragonMajesty.groovy, src/tcgwars/logic/impl/gen7/GuardiansRising.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
* Phione (DRM 30) should remove conditions from the affected Pokémon, not itself.
* Attempted to correct Octolock's checks (SSH)
* Meowth (DS 77) should take any energy from discard, not just basic ones.
* Attempt on Oricorio (GRI) at checking for discardselfEnergy happening. Needed for other cards allowing to attack for free (e.g. Copy). Also affects:
+ Cresselia (UPR 59)
+ Torkoal (CEC 29)
+ Morpeko V (SSH 79)
+ Not quite, but also Lapras V (SSH 49)
=> Some more Fixes (DRM, SSH, DS, GRI)

src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
* Fixed Abra (MT 69) failing to show top 5 cards of deck due to a typo
* Fixed Wacan Berry in Bidoof (MT 73)
* Cleaner module for Dragon Rage on Magikarp (MT 89) [Thanks flagrama!]
* Pikachu (MT 94): Electro Recycle should be once per turn.
* Fixes on Fossil Excavator (MT 111)
=> MT Fixes (69, 73, 89, 94, 111)

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen1/BaseSetNG.groovy, src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen3/UnseenForces.groovy, src/tcgwars/logic/impl/gen4/HeartgoldSoulsilver.groovy, src/tcgwars/logic/impl/gen7/BurningShadows.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/GuardiansRising.groovy, src/tcgwars/logic/impl/gen7/ShiningLegends.groovy, src/tcgwars/logic/impl/gen7/SunMoon.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy, src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
If it works, need to apply to other cards like Guzzlord (CEC).
* Now should give the extra prize before the opponent chooses a new active.
* Removed an unnecessary afterDamage (there's no damage)
* Updated the bc to mention the extra damage enabled, and the eventual secondary effect.
This shouldn't be done after the damage, otherwise cards like Horror Psychic Energy (RCL 172) will trigger when they shouldn't. 
> Q. If I use an attack that says to "discard an Energy attached to your opponent's Active Pokemon" and I choose to discard their "Dangerous Energy" card, would I still receive the 2 damage counters from "Dangerous Energy" or not?
>
> A. You would not receive the 2 damage counters. (Ancient Origins FAQ; Aug 13, 2015 TPCi Rules Team)
Affects multiple cards:
* Poliwrath (BS) [Both …
=> Opp's Active Energy Discard OoO fix, ADP extra prize order fix

src/tcgwars/logic/impl/gen7/TeamUp.groovy
Fixed Adventurous Appetite to shuffle opponent's deck instead of player's deck after use.
=> Alolan Muk bug fix

src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/GuardiansRising.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
Now should give the extra prize(s) before the opponent has to pick a new active. Affected cards:
* Arceus & Dialga & Palkia-GX (CEC 156)
- Removed an unnecessary afterDamage (there's no damage)
- Updated the bc to mention the extra damage enabled, and the eventual secondary effect.
* Guzzlord (CEC 136)
- Now also does a bc on effect activation.
* Guzzlord-GX (CIN 63)
* Whimsicott (GRI 91)
* Beast Bringer (UNB 164)
* M-Sableye & Tyranitar-GX (UNM 126)
* Implemented twister in a cleaner way, or updated old ones in:
- Dragonair Delta (DS 42)
- Gyarados-ex (FRLG 109)
- Dragalge (FLI 53)
- Dragonair (TEU 118)
- Dragonair (UNM 149)
* Made some attacks targeted:
- Pelipper (CES 112)
- Tornadus-GX (SMP SM134)
- Trevenant & Dusknoit-GX (SMP SM217)
- Lucario & Melmetal-GX (UNB 120)
- Inteleon (SSH …
=> Prize-taking priority fixes, and some other general fixes

src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
Pale Moon GX currently affects Pokémon that are ignoring effects from
attacks.
=> Trev/Dusk GX SM217 - Attempt to fix Pale Moon GX

src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
If you knock out an opponent's Pokémon in the middle of your turn, your
Rosa cards' `Rosa_KO` is overwritten with the current turn, which will
no longer allow you to use your Rosa card. This prevents that conflict.
=> Rosa CEC 204 - Use keyStore

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen4/DiamondPearl.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen4/RisingRivals.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy, src/tcgwars/logic/impl/gen4/Triumphant.groovy
* Make Leech Seed on Cherubi (DP 75) last priority.
* Added a temp debug bc for Fossil Excavator (MT 111), to find why it crashes when selecting a stage 2 card on search.
* Fixed Retreat Cost for Pikachu (MT 94).
* Made Chesto Berry prevent the next sleep coinflip on Buizel (MT 75). Right now it checks even though the condition is already gone.
* Partially implemented Vigoroth (MT 68). It should also check for Slakoth having been asleep before evolving that turn.
* Magmortar LV.X (MT 123) should override the burn damage value to 30, not plainly increase it. Other burn cards should also do the added check for the value not being already increased as much or even higher than needed.
* Have Budew (DP 43) assert having deck before using Errand-Running
* Fixed Nidoran names in all DP-era sets, …
=> Some DP/MT fixes, Implemented MT 1-67

src/tcgwars/logic/impl/gen3/Deoxys.groovy
Open to feedback, multiple minor fixes, but some are more substantial.
Will undraft it once I finish checking the other 30~ cards in the set.
* Regarding Master Ball (EX 88):
- This is a weird one. On one hand, the EX Compendium has a 2005 ruling saying that picking a Pokémon card found among the top 7 cards was mandatory:
> Q. The wording on the new Deoxys verison of "Master Ball" says, "...Choose a Basic Pokémon or Evolution card...". However, the wording on the older versions say, "...you MAY choose..." Does this mean now that if you draw a Pokémon you MUST take it, or should it still be a choice?
>
> A. Sorry, you no longer get to choose. You MUST take a Pokémon if you draw at least one. (Apr 14, 2005 PUI Rules Team)
- **_However,_** deck content is private knowledge, and future …
=> EX Deoxys set fixes

src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy, src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen3/UnseenForces.groovy, src/tcgwars/logic/impl/gen7/BurningShadows.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/SunMoon.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy
Should correct issues with "treat that card as a Basic Pokémon", namely:
* Holon Fossil (HP 86)
* Anorith (LM 29)
* Strange Cave (LM 77)
* Omanyte (PK 56)
Many cards across the EX-era files were coded using `pcs.basic`, while many others used `!pcs.evolution`. Checking around, the correct definition for these attacks would be "Basic Pokémon [in Play]: Not an evolved card". There's no need to add/remove "BASIC" or "STAGE 1" cardTypes, the bottom intent of that text in the above cards' effect is not considering them as evolved. On the opposite side of the spectrum, Baby cards using "Baby Evolution" make the Basic put on top of them count as an evolved Pokémon, even though being a Basic Pokémon _card_:
> Q. Say I use my Pichu's "Baby Evolution" power to evolve Pichu into Pikachu, which is …
=> Made some EX-era cards look for that time's definition of "Basic Pokémon" [in play], also a similar thing but for SM-era cards and "Evolution Pokémon"

src/tcgwars/logic/impl/gen1/JungleNG.groovy, src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy, src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen3/UnseenForces.groovy, src/tcgwars/logic/impl/gen7/BurningShadows.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/DragonMajesty.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/GuardiansRising.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
* Tri Attack-GX on Alolan Muk-GX (BUS 84) can be used regardless of the opponent having bench.
- This is an important fix (and might need to check around other GX attacks where this may apply), due to it allowing attacks (in cards like this one, a free attack) that enable boosts on cards like Hala.
- Relevant ruling:
> Q. If my opponent has no Benched Pokemon, can I still use Alolan Muk-GX's "Tri Hazard-GX" attack?
>
> A. You can use it, but it won't have any effect, and it will count as having used your GX attack for the game. (Burning Shadows FAQ; Aug 3, 2017 TPCi Rules Team)
* Fixed "Extra Prize" check on multiple cards being done after KOs instead of before them. Should fix opponent choosing the new active before the extra prizes are taken. Cards affected:
- Guzzlord (CEC 136)
- …
=> [Ready for Review] Various Fixes

src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Apparently `self` is only a construct for Pokémon cards? Trainer cards
only have `thisCard` it seems.
=> Rosa CEC 204 - Use thisCard in playReq too

src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Although it'd be more correct to ensure the supporter card is played from hand, I think that is the part of this check that is failing. If this fixes it not applying the damage then this solution should work well enough for now.
=> Sylveon CEC155: Remove seemingly non-working check

src/tcgwars/logic/impl/gen3/LegendMaker.groovy
Now checks for special conditions, and removes the damage counter even if it's blocked on the receiving end.
=> Fixed Banette ex (LM 85)

src/tcgwars/logic/impl/gen3/UnseenForces.groovy
Black Cry no longer blocks all of opponent's PokePowers, just their active's.
=> Fixed Umbreon ex's Black Cry

src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
`[]` is an ArrayList by default. Explicitly create an empty `CardList`.
Pokémon was still in the same position in deck after the selection. Try to explicitly move it to the new `CardList` instead of just adding to the list. May need to add `hidden` key to this.
=> CELEBI_SM224 Fixes

src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy
Pow! Hand Extension is no longer disabled by cards that prevent effects of attacks
=> Fix to Pow! Hand Extension

src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Just a couple of things.
- Rowlet
- I'm just guessing that `thisCard` and `self` are different somehow and that's why the `keyStore` didn't work.
- `opp.bench.select` was thinking select was a property. Explicitly using parenthesis now, so shouldn't have any issues, but unsure of why it wasn't working without them.
- Decidueye
- Explicitly check self instead of trying to rely on the argument to the effect
- Shorten the lines
=> Darkness ablaze quick fixes 2

src/tcgwars/logic/impl/gen3/LegendMaker.groovy
Giant Stump's effect now goes away once discarded. I think `delayed` may have been causing the problem here.
=> Giant Stump fix

src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen4/HeartgoldSoulsilver.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
Also left a couple TODOs to request appropriate images
for some of the cards that provide more than one type,
but do not provide RAINBOW.
In theory `owner` should be the closure above the current closure. If this doesn't work, I have several other ideas to attempt this.
Also changed HGSS Rainbow to a copy of CES Rainbow since I'm done testing with it and having only one implementation is probably a good idea. I changed Capture energy to not have a type while not attached to a Pokémon (according to card text) and added a getEnergyTypesOverride for it to provide its C energy.
=> Ensure Special Energy show proper types

src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Still not sure what exactly causes it to require parenthesis in some cases, but not in most others.
=> TSAR_16 DAB - More required parens

src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
Special energies that are supposed to only provide energy while
being attached to a Pokemon now do so properly.
Twin Energy now also "provides" 2 C energy while not attached instead of just 1 C.
=> RCL, SSH - Fix special energies

src/tcgwars/logic/impl/gen3/Deoxys.groovy
Heal Energy's effect no longer works when attached from discard
=> Heal Energy Fix

src/tcgwars/logic/impl/gen3/Emerald.groovy
Emerald version was causing a Game Engine Error. Sandstorm version is working fine as far as I can tell.
=> Lanette's Net Search references Sandstorm version

src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy
No longer crashes game when player fails search.
=> Fix to Surprise Time Machine

src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
When using energy providing multiple values you should be able to
choose how many of the provided energy count towards the cost
mentioned in the attack text.
Ex: With two Counter Energy attached while behind on prizes you
should be able to choose to discard both Counter Energy instead
of being forced to choose only one of them.
=> SUIC_39 DAB - Allow proper cost choice

src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy
Based on various rulings it seems that in Generation 3 and earlier, if a Pokémon card is in play it is considered Basic if it is not evolved. The Basic type on the card only matters while not in play. Generation 4 and on strictly goes by the card saying Basic on it.
These changes bring a few more cards that were checking for the cardType in line with this belief. This should mean that the cards STRANGE_CAVE, and ANORITH from Legend Maker, HOLON_FOSSIL from Holon Phantoms, and OMANYTE from Power Keepers should work as intended with the cards used in their original format.
However, this will be the first time notEvolution has been used in the codebase, so it may not work and need to be replaced with `![...].evolution`
=> Mark as basic alternative

src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy
Using the owner property of the getEnergyTypesOverride closure was a neat idea, unfortunately it doesn't get called often enough to stay updated properly it seems. This _should_ show the right icons, and hopefully be updated at the right times.
=> Fix energy icons not updating early enough

src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy
This PR will address the issues with Mysterious Fossil in Holon Phantom and Legend Maker regarding the use of the wrong image and the HP value being only 10 instead of 50.
=> Fix Mysterious Fossil (HP & LM) Image and HP Value

src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy
Reverts axpendix/tcgone-engine-contrib#755
This seems to just break special energy instead. I guess the delayed update is the best option at the moment? Will need to ask @axpendix if there is a way to refresh more frequently. Seems to only refresh the images when the energy count are read due to using an attack or similar.
After this revert, when two counter energy are attached and you are behind on prizes, both will show as a single colorless if attached before you were behind on prizes. IIRC one attached after will use the correct image, but I'll have to verify that after the revert. Trying to use an attack that requires a certain type of energy will evaluate the Energy which prompts the override, but it doesn't seem to reevaluate all of the energy? It seems like it evaluates enough to …
=> Revert "Fix energy icons not updating early enough"

src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
Relevant Ruling:
Q. If Garchomp Lv.X uses its "Restore" to bring up Ninetales
(Delta Species) from the discard pile, can Ninetales use its
"Volunteer" Poke-POWER to find another Ninetales or Ninetales-EX?
A. No. The Volunteer Poke-POWER must be able to leave a Vulpix in
play. (May 29, 2008 PUI Rules Team)
=> NINE_D_8 DF - Must have Vulpix underneath

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy, src/tcgwars/logic/util/PokemonCardSet.java
Placed it in some cards from Cosmic Eclipse as examples.
* ~~Could probably use a "type filter" param, since a couple of cards make use of it (Like N's Resolve in the examples).~~ Already implemented into the draft.
* ~~Another potential param filter could be for "Pokémon ex/LV.X/EX/GX/V/VMAX", since a couple cards search for those specifically (See: Great Catcher CEC 192)~~ Implemented as well, just for EXs/GXs/Vs tho. More can be added later on, if needed, without much trouble.
- Implemented isPokemonV() and isPokemonVMAX() on PCS for this to work
=> assertAnyPokemonInPlay() static method, isPokemonV() / isPokemonVMAX() PCS methods

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Figure this won't break anything and makes `switchYourActive` more flexible, but want to make sure it won't.
=> Add source param to switchYourActive, use for BIRD_KEEPER

src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy
Attaching energy cards with Extra Energy Bomb is no longer optional
=> Electrode ex fix

src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Altering your own Energy while attacking happens after damage. Altering your opponent's Energy happens before damage. This is a quick PR to ensure this happens. Relevant mainly for Tsareena and returning Horror Energy to hand, and Zygarde with discarding Strong Energy while attacking.
Also attempting to use `afterDamage` inside of `if` statements to ensure this without breaking the flow of the code forcing you to reference back and forth. I don't forsee this breaking anything, but want to make sure this wasn't attempted before and ended up breaking something.
Relevant Rulings:
> Q. If I have Strong Energy attached to a Fighting type Pokemon and use an attack that says to discard an energy, do I get the bonus damage from Strong Energy before I discard it or not?
A. Yes, you do. (Furious …
=> General DAB: Alter self energy after damage, opponent before

src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy, src/tcgwars/logic/impl/gen4/DiamondPearl.groovy, src/tcgwars/logic/impl/gen4/RisingRivals.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
* Fixed Gengar (SSH) not using powerUsed()
* Fixed a wrong copy in PK
* Fixed an Engine Error in two cards (DAB, RR)
* Attempted a fix for the Roto Motor ability of UPR/FLI Rotoms
* Attempted a fix for LV.X cards in DP-Base.
* Test fix for Nintendo era cards not blocking Wizards era Pokémon Powers
=> Multiple Fixes (EX, SSH, DAB, UPR+FLI)

src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen4/CallOfLegends.groovy, src/tcgwars/logic/impl/gen4/MajesticDawn.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen4/RisingRivals.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy, src/tcgwars/logic/impl/gen4/Undaunted.groovy
Now DP-era prints should follow the Mysterious Treasure print, which only does its effect when attached to [D] Pokémon. The EX Emerald print now properly works on those as well as on Pokémon with "Dark" in their name.
Also fixed most references to these two prints, from their relative reprints. Only missing ones for EM is the "EX Ruby & Sapphire" set, which is not made in Groovy so can't be fixed by this PR.
=> Fixes for Darkness Energy [Special] (EM and MT prints)

src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy, src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
More optimal prevent, now checks for Pokémon played that same turn.
=> One more LV.X fix, and Fixed Nidoqueen Delta

src/tcgwars/logic/impl/gen7/BurningShadows.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Just as the LV.X devolution workaround, this is only additional checks and can be easily tracked and removed once no longer needed.
=> Added temp workarounds for VMAX filtering in Stage 1 checks

src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy, src/tcgwars/logic/impl/gen7/BurningShadows.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy
Fixes for Ninetales (TEU), Sophocles and Plumeria (BUS), Mysterious Treasure (FLI) and Mars (UPR) based on a batch of rulings added about a year ago to the compendium, clarifying whether their initial discard is an effect in itself or a cost. More details for it at https://pokegym.net/index.php/2019/04/01/trash-talk/.
=> Requirements fix for multiple SM era cards, fix attempt at Shiftry ex (CG 97)

src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
* Mamoswine (Crimson Invasion) now puts damage counters on itself only after damaging the opponent's Active Pokémon. Now works like Froslass (Unified Minds).
* Charizard and Incineroar-GX (Team Up) should search and attach all energy before checking for it being KO'd. Also optimized Charizard's search.
> Q. If I use Charizard's "Roaring Resolve" Ability with only 10hp left, does he get KO'd when I place the 2 damage counters before or after I search & attach 2 {R} Energy cards?
> A. You must finish all the text of the Ability before checking for knockouts, so yes you would search your deck and attach {R} Energy cards before KO'ing Charizard. (Team Up FAQ; Jan 31, 2019 TPCi Rules Team)
* Naganadel & Guzzlord-GX (Cosmic Eclipse) and Naganadel-GX (Unified Minds) can now discard an Ultra …
=> Multiple SM card fixes

src/tcgwars/logic/impl/gen3/UnseenForces.groovy
If this works properly, I would only use it as a static for attacks requiring multiple big numbers of energy discarding. Singular discard are 100% fine with discardSelfEnergy. And this'll skip unfullfillable requirements, so copy attacks that don't use the original attack-cost may be able to skip part of the discard effect. Shouldn't happen for those in EX era like Copy though (I think).
Steps of operation:
* Collect all "potential energy", aka all the individual Energy Sets (e.g. 2 potential rainbows for a Double Rainbow **Energy card**, or a Holon's Castform)
* Remove all requirements that can't be fulfilled (no potential energy can cover it).
* Sort requirements, prioritizing those that have less fulfillment options across the potential energies available.
* Begin selecting. For each …
=> Implementation attempt at Elemental Blast (Lugia-ex, UF 106)

src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
* First, regarding Tyranitar: Added some extra checks just so it has more verbose regarding a Pokémon already having a marker (it should be a valid target tho, even if useless). No Shockwave checker as with Imprison, but if that works I'd just make a variant for it.
- Note: Might be worth allowing to attack if any Opponent's Pokémon has a marker, but show all Pokémon and loop until one with Shockwave is selected for the KO (as to keep consistency with the checker, in case multiple identical Pokémon exist with and without markers)
* Imprison's global Body/Power block and check action should register only once per game. These should remain even if said Gardevoir is knocked out, and not duplicate if another comes into play (before one enters play, there should be no way to replicate the …
=> Attempt at Imprison implementation, changes to Shockwave and potential way to check until markers are added

src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Applied some erratas:
- Added some comments and edited card text for more clarity (so they're not unerrata'd by mistake)
- Now Mantine (TRR 45) can only use Ripples from the Active Position:
> * Mantine's Poké-POWER only works when it is the player's Active Pokémon. Official Wording: Once during your turn (before your attack), if Mantine is your Active Pokémon, you may remove 1 damage counter from 1 of your Pokémon (excluding Mantine). This power can't be used if Mantine is affected by a Special Condition. (Dec 16, 2004 PUI Announcements)
- Mt. Moon (FRLG 94) now affects Pokémon with <= 70 HP, instead of just < 70:
> * Mt. Moon should read: "Any Pokémon (both yours and your opponent's) with maximum HP of 70 or less can't use any Poké-Powers." This errata replaces text of "less than 70" …
=> Applied some Erratas (TRR, FRLG), plus some notes for a couple already implemented

src/tcgwars/logic/impl/gen7/CelestialStorm.groovy
For some reason, this card has been missing since Celestial Storm's release. :(
Bringing it back though. Should be good to merge immediately, this was already in carddb and also already has a scan up
=> Add secret rare Rainbow Energy to Celestial Storm

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen3/UnseenForces.groovy, src/tcgwars/logic/impl/gen4/DiamondPearl.groovy, src/tcgwars/logic/impl/gen7/BurningShadows.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/GuardiansRising.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/ShiningLegends.groovy, src/tcgwars/logic/impl/gen7/SunMoon.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
Many (but not all) attacks, abilities and poké-powers/bodies trigger a switch effect that's applied to the benched Pokémon. `sw` on itself is triggered for both switched pokemon as an ATTACK/TRAINER_CARD/SRC_ABILITY effect **(Update: This may not be accurate, tho a change is still needed.)**. ~~Using [swFromBench](https://github.com/axpendix/tcgone-engine-contrib/blob/0b6c994535cdb5fa4d44ea5d42ddfa0ba6ab21d1/src/tcgwars/logic/groovy/TcgStatics.groovy#L442) handles the targeting part on itself, and also provides a boolean return for when a following effect depends on the switch being successful or not (Drag Off and Guzma being prime examples).~~
**Update: Switched to a `sw2` method after talking with @axpendix, as sw already returns a boolean. `sw2` will return false if the switch is …
=> Fixed conditional switches from bench to active

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen1/BaseSetNG.groovy, src/tcgwars/logic/impl/gen1/FossilNG.groovy, src/tcgwars/logic/impl/gen1/TeamRocketNG.groovy, src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy, src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen4/DiamondPearl.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen7/BurningShadows.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/GuardiansRising.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy, src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy, src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy, src/tcgwars/logic/impl/pokemod/PokemodBaseSet2.groovy
First commit is pretty straightforward, just adds `after DEVOLVE` unregisters. I think they're needed in all modified cards but let me know if you think some shouldn't.
Regarding other commits: One situation I noticed on some cards is the effect remaining on the new active on certain situations. While maybe unnecessary, setting a pcs variable pointing to the specific... well, PCS, should make it work more reliably in theory, at least in my opinion. Also includes some changes in some implementations, beyond the DEVOLVE check above.
=> Multiple card fixes, revolving around adding DEVOLVE checks (but more stuff on a couple separate commits)

src/tcgwars/logic/impl/gen7/SunMoon.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy
Related ruling:
> Q. If I use Welder and attach a Fire Energy to an Eevee that has the "Energy Evolution" Ability, do I draw the cards for Welder first or search for a Flareon due to "Energy Evolution" first (or is it a choice)?
> 
> A. Since they are simultaneous actions, it is the player's choice of which order they can do this. (May 9, 2019 TPCi Rules Team)
A similar logic would need to be added to the other Energy Evolution cards (Definitely the XY-Furious Fists Eevee, also the Neo Discovery and Unseen Forces prints whenever Unlimited includes SM sets)
=> Make Energy Evolution (Eevee SUM) handle timing conflict with Welder

src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Not 100% liking this implementation (since the card ends up in the hand for a brief moment), but it should work fine. Hopefully the global value stops Jirachi appropriately.
=> DAA: Implement Mountainous Smoke, plus some fixes

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen1/TeamRocketNG.groovy, src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy, src/tcgwars/logic/impl/gen4/SupremeVictors.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/DragonMajesty.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
Moved some stuff from #888, and started working on some other more immediate fixes (the switch changes are a bit larger, I'd rather leave those on its own PR without these mixed in-between.)
Fixes to confirm working once merged: 
+ Made it so both this one and the Ultra Prism print no longer allow moving a counter from a Pokémon to the same one (which didn't make a lot of sense)
=> General Fixes

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen1/BaseSetNG.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen7/BurningShadows.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy
These are playable, so restrictions were removed. Instead, now a warning is displayed about the game loss risk.
Main case for this is EX era, a player may wanna burn some super scoop ups as to be able to use Steven (even if risking a loss).
Tested already, working properly in dev.
=> Added confirmation for scoop effects that may cause a game loss

src/tcgwars/logic/impl/gen1/BaseSetNG.groovy, src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen3/UnseenForces.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen4/Unleashed.groovy, src/tcgwars/logic/impl/gen7/DragonMajesty.groovy, src/tcgwars/logic/impl/gen7/GuardiansRising.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy, src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
Should now properly detect the targeted PCS, and prevent only when meant to. Fixes some issues related to "gust of wind" effects.
=> Fix some SPC prevention logic

src/tcgwars/logic/impl/gen3/PopSeries2.groovy, src/tcgwars/logic/impl/gen3/PopSeries5.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
+ Commented the old code, since Groovy Implementation of Technical Machines is still a TODO.
These fixes have been tested locally.
=> Some more fixes

src/tcgwars/logic/impl/gen4/Unleashed.groovy
This fixes the crash when using Megaton Tail on `TYRANITAR_88` from Unleashed.
=> Update TYRANITAR_88 to not crash during Megaton Tail attack

src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/util/PokemonCardSet.java
Needed to fix a UI bug, after adding HP info when hovering over the damage counters meter.
When the value is requested in-game, the cached value is updated. Then the StatusPanel can access this value consistently.
=> Add getLastFullHP() method for PokemonCardSet

src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/HiddenFates.groovy
Multiple Hidden Fates fixes. Large refactor of Weezing's "Surrender Now" ability, and by extension the Jessie & James supporter.
Also fixed Koffing from CEC's ability being able to be triggered when discarded by Roxie even if it should be blocked.
=> Hidden fates fixes

src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
PR for #908.
Stops Evosoda and Rare Candy from allowing evolving from a D Pokémon to evolve to a non-D Pokémon. Sandstorm Rare Candy still gets discarded, but modern Rare Candy does not. Evosoda gets discarded, but since you search your deck with it that's fine.
This Ability is a beast.
=> Fix Rare Candy and Evosoda allowing to evolve from D to non-D

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen4/DiamondPearl.groovy, src/tcgwars/logic/impl/gen4/MajesticDawn.groovy, src/tcgwars/logic/impl/gen4/Unleashed.groovy, src/tcgwars/logic/impl/gen7/BurningShadows.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/ShiningLegends.groovy
Moved the Neo Genesis code into this publicly-available print. Should work properly with certain abilities (Like Infinity Zone) with the changes applied here, and to removePCS(pcs)
=> Point all Super Scoop Up prints to the FRLG version, update removePCS(pcs) static

src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Fix null pointer errors
Fix blocking opponent's evolution
Fix not updating bench when scooping up a non-D pokemon properly with a hack
=> Fix eternatus ability and spikemuth

src/tcgwars/logic/card/Collection.java, src/tcgwars/logic/impl/gen3/NintendoBlackStarPromos.groovy, src/tcgwars/logic/impl/gen4/DiamondPearlPromos.groovy
Also added missing EX tags, marked all rarities as PROMO, and changed the numbering to match cards (which use 3 digits with left zero padding). Applied similar changes to Diamond Pearl Promos, as to enable DP01-DP05 in the "2007 (DX-DP)" Worlds format.
Also added NINTENDO_BLACK_STAR_PROMOS to Collection.java, as to make these available in the corresponding formats (updated in the related PR for core).
=> Implementations for Nintendo Promos 001 to 040, plus some fixes for DiamondPearlPromos

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen1/BaseSetNG.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen7/BurningShadows.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/SunMoon.groovy, src/tcgwars/logic/impl/gen7/TeamUp.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/util/BenchSet.java
The TCGStatics change may need a second revision, this was just done quickly to reduce issues the ability blocking a RemoveFromPlay in a RemovePCS was running into.
Mr Mime's Scoop-Up Block should work in nearly every case that discarding doesn't happen _and_ need to be prevented by the ability. That remaining case is handled using special cases where the scoop up trainers are concerned, but depending on a future ruling, may or may not need changed to be more general somehow for say Wishiwashi SUM's ability.
Lastly, updates Recycle Energy (UNM copy only) and U-Turn Board to go prevent the MoveCard to discard effect if a MoveCard to hand effect succeeds instead of going to discard, then being moved to hand.
=> Scoop up block

src/tcgwars/logic/card/CardType.java, src/tcgwars/logic/card/Collection.java
* Updated the short name of some Collections/Sets:
- Furious Fists (FUF -> FFI) and Primal Clash (PCL -> PRC) now use the official shortname used in other sites, including the official ones.
- BW Black Star Promos (BLWP -> BWP) and SWSH Black Star Promos (SSHP -> SWSHP) are now consistent with other Black Star Promos such as the XY and SM ones, improving consistency across them.
- Shiny Vault doesn't have an official short name. The set code used is the one from the original set so a custom, clearer one like the one in RUMBLE is used now (SV would've been preferable, but it's taken by Supreme Victors; SHINYV guarantees it won't conflict with any future set, hopefully)
* Reordered the TRAINER and ENERGY top CardTypes
- This is needed for some Deck Import/Export changes to work consistently …
=> Update short name for some Collections, reorder TRAINER and ENERGY in CardType

src/tcgwars/logic/impl/gen7/TeamUp.groovy
The attempt to retain the targeted Pokémon through effects didn't work properly. It would get confused if, say, you devolved a undamaged Pokémon, then a damaged one with your opponent having Scoop-Up Block active. It would not block the second one properly and allow you to scoop it up anyway.
Instead, I use the tried and true method of "just find the card in one of the opponent's PCSes, and use that PCS as the target"
=> Fix at least devolution not using the proper target

src/tcgwars/logic/groovy/TcgStatics.groovy
Returning in a closure returns the value of that closure. Need to return the result of the closure instead. Since run returns `false` for success, need to invert it as well.
=> Correct return value of scoopUpPokemon static

src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
This PR will correct when Dynamic Swing unregisters so that it will occur after the opponent's turn ends.
Currently doing two Dynamic Swings will cause the effect to incorrectly stack, taking +100 more damage for each time it's used it.
=> Fix UNM SLAKING_170 Dynamic Swing Not Unregistering

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen8/ChampionsPath.groovy, src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy
Added documentation to `attachEnergyFrom` and updated some documentation in TcgStatics because it was hard to read in IDEA's intellisense-like feature. Would like to find a way to actually display map keys in said UI, but knowing that it is a map should be enough to look up what is needed.
Implemented the rest of the cards in the set. Seems like another basic and boring set like Hidden Fates, so wasn't too difficult 🤣 
Tried to specify copies a bit better. Was confusing which ones were actually in the current file and which ones were actually in other files. At some point we need to make sure we don't have any duplicate code for reprints. e.g. Some Poké Ball cards copy from FireRedLeafGreen, some copy from EmergingPowers.
=> Champions path

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen1/BaseSetNG.groovy, src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy
* Pluspower (Base Set) should now only be attachable to the Active Pokémon, not any in play.
* Devolve now only is ran after the devolve static finishes (and isn't blocked). This should return old functionality in cards reacting to this event (without reverting/altering the changes recently made for Lv.X/scoop-up-block support).
* Some cards reacted before the DEVOLVE effect, which did nothing prior or after recent changes. They now should work correctly. This includes Imprison/Shock-Wave marker removal, Aegislash (Forbidden Light) and Deoxys ex (EX Deoxys)
- Note here: Ditto (Vending), Ditto (Fossil) and Brock's Ninetales might have issues when a devolve is attempted on them. Those `before DEVOLVE` checks should be tested/looked at and either fixed. reworked or outright removed. This …
=> Fix Pluspower (Base Set), move Devolve Effect timing so cards that wait for it work properly

src/tcgwars/logic/impl/gen3/UnseenForces.groovy
This PR introduces a change to Stantler's Push Away move so that it will be more convenient to use by removing the need to show the same card list prompt twice
=> Update Stantler's Push Away Ability

src/tcgwars/logic/impl/gen8/SwordShieldPromos.groovy
The [first commit](https://github.com/axpendix/tcgone-engine-contrib/commit/8528eb8bc8460c529c3f3f39632d01f7b3a3f971) contains all of the known promos for future reference. I pruned it down to only the released ones in the second commit so as not to break street dates, cause trouble, broken card images, etc. Galarian Farfetch'd V's ability relies on #965 so I didn't fully implement it, but it also doesn't release for a couple weeks anyway.
Is there actually any cases where the TODO on Eevee actually is relevant though? I'm pretty sure I've asked before, but don't remember the answer.
=> Implement SWSH promos 2020 oct 03

src/tcgwars/logic/impl/gen8/AmazingVoltTackle.groovy
This PR adds the groovy template for the Japanese set `Amazing Volt Tackle`.  
This file will never be used for production directly, but it will speed up development for the English set `Amazing Voltage` since we can call `copy()` for the entries in this set.
Also, this was automatically scrapped from [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Vivid_Voltage_(TCG)) using my script (`Beautifulsoup` for the win).  
With my new script, we can easily repeat this process for new Japanese sets later on and speed up development.
=> Initial Amazing Volt Tackle Groovy Template

src/tcgwars/logic/card/Collection.java
This gives us the opportunity to add sets to the server without making them visible in the deck editor and play server card database.
Just add a new item to the list of dev-only IDs in the private method and the public one should return the list of all other expansions.
=> Add method to only get the live expansions

src/tcgwars/logic/card/Collection.java
This should fix the jumbled mess currently displayed on the play server card database and inventory dropdowns.
=> Use TreeSet to automatically order the non-dev Collection set

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
This PR introduces the changes to move the GlobalAbility for holon energy-pokmon (Holon's Voltorb, Holon's Castform, etc) into something more reusable inside TcgStatics.
These changes also update the logic of how attachment works so that it will not interfere with other Ability-based energy attachments such as Meganium Ex's `Nurture and Heal` ability.
This PR is dependent on PR https://github.com/axpendix/tcgone/pull/109 which allows the PlayEnergy effect to have the energy attachment target defined by the caller.  
It is used in these changes to determine if the Holon's Energy-Pokemon can be attached or not.  (clarification: it should not be allowed if an energy has already been played for the turn)
=> Refactor Holon-Energy Pokemon Global Ability

src/tcgwars/logic/groovy/TcgStatics.groovy
Fix Holon Energy Pokemon static so that Holon Magnemite and Voltorb won't need to return energy when Attached
=> Update Holon Energy Pokemon Static

src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen3/UnseenForces.groovy, src/tcgwars/logic/impl/gen4/CallOfLegends.groovy, src/tcgwars/logic/impl/gen4/HeartgoldSoulsilver.groovy, src/tcgwars/logic/impl/gen4/MajesticDawn.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen4/Platinum.groovy, src/tcgwars/logic/impl/gen4/RisingRivals.groovy, src/tcgwars/logic/impl/gen4/Stormfront.groovy, src/tcgwars/logic/impl/gen4/Undaunted.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy, src/tcgwars/logic/impl/gen8/AmazingVoltTackle.groovy, src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy, src/tcgwars/logic/impl/gen8/LegendaryHeartbeat.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy
All of the Special Energy except for Burning Energy should now be blocked by Miraculous Wind and Spectral Breach.
Relevant Rulings [all from the Japanese Q&A](https://translate.google.com/translate?sl=auto&tl=en&u=https://www.pokemon-card.com/rules/faq/search.php?freeword%3D%25E3%2582%25B4%25E3%2583%25BC%25E3%2582%25B9%25E3%2583%2588%25E3%2583%2596%25E3%2583%25AA%25E3%2583%25BC%25E3%2583%2581%26regulation_header_search_item1%3DBW) for many decisions on what should be blocked (basically everything) and what should not (costs _before_ playing) though Rainbow Energy has rulings against it working this way, I took some creative liberty with it because of how similar it is to other "do _on_ attach" abilities, especially in wording. Though I have asked for a ruling on it here: …
=> Light Dragonite and Dusknoir

src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen3/UnseenForces.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen8/AmazingVoltTackle.groovy
Shiftry's Ability Only While Active
Simplify Unown E (UF) Hidden Power attack
* Should no longer double prompt the player. Will show the full hand
whether there is a Basic in hand or not. Message changes based on
whether a Basic is available or not as well.
Rocket's Wobb (TRR) Simplify and fix Dark Aid
* Simplified some repetitive code. Fixed Dark Aid not checking for
Rocket's Secret Machine cards. Fixed Dark Aid not always allowing
you to shuffle the cards to deck.
Clefairy (CEC) fix scoop up timing
Shedinja (VIV) playable with ability turned off
=> Bug fixing

src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy, src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
The safeguard static is for BW-era EXs. The Safeguard effect already
exists for EX-era exs, so we can use it for the relevant cards. I'm not
sure if the existing pokeBody closure should be removed?
=> Use Safeguard effect for EX-era implementations

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen8/AmazingVoltTackle.groovy, src/tcgwars/logic/impl/gen8/ChampionsPath.groovy, src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy, src/tcgwars/logic/impl/gen8/LegendaryHeartbeat.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy, src/tcgwars/logic/impl/gen8/SwordShieldPromos.groovy
Implements the new SelectEnergy effect to handle discarding/moving Energy after damage properly. Energy is selected before damage, damage is applied, then energy is discarded/moved when these statics are used.
Implemented primarily in the gen8 sets for now, and replacing some TODO's left from a former non-static, non-SelectEnergy implementation in other sets. If all seems well, another PR will be made to try to massively replace existing improperly handled Energy discards/moves.
=> Discard energy after damage

src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Fixes Phione crashes. used sw2(opp.active, opp.bench.oppSelect(...),SRC_ABILITY) rather than sw2(opp.bench.oppSelect(...), null,SRC_ABILITY) as it should target your opponent's active Pokemon. @axpendix 
[phione.txt](https://github.com/axpendix/tcgone-engine-contrib/files/5611729/phione.txt)
https://forum.tcgone.net/t/br-phione-smp-sm220-lucario-melmetal-gx-smp-sm192-phio/11188
=> Phione crash fix

src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy
https://forum.tcgone.net/t/br-blacephalon-smp-sm221-sudowoodo-lot-110-game-engine-e/11196
=> Fix Beast Energy crash

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy, src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy, src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/PopSeries1.groovy, src/tcgwars/logic/impl/gen3/PopSeries2.groovy, src/tcgwars/logic/impl/gen3/UnseenForces.groovy, src/tcgwars/logic/impl/gen4/Arceus.groovy, src/tcgwars/logic/impl/gen4/DiamondPearl.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen4/Platinum.groovy, src/tcgwars/logic/impl/gen4/PopSeries8.groovy, src/tcgwars/logic/impl/gen4/Stormfront.groovy, src/tcgwars/logic/impl/gen4/Unleashed.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy, src/tcgwars/logic/impl/gen7/DragonMajesty.groovy, src/tcgwars/logic/impl/gen7/GuardiansRising.groovy, src/tcgwars/logic/impl/gen7/HiddenFates.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
Uses the new overload in places where it is appropriate to use in existing code.
Also adds text to ones missing it. Was done by just using the text property of the attack that is using it, but should provide better context.
=> Use the new multiSelectPokemon Overload

src/tcgwars/logic/util/CardList.groovy
Only create shuffled copy for hands when selecting from a hidden cardlist
=> Fix Cardlist Shuffle on Select

src/tcgwars/logic/impl/gen3/Deoxys.groovy
Dragon and NeoRev prints are handled in Retreat and work (mostly) properly currently. Deoxys is a reprint that should function identically.
=> Balloon Berry (Deoxys): Set as reprint

src/tcgwars/logic/impl/gen8/ShinyStarV.groovy
In all other instances where "hp" is used, the number is wrapped in parentheses. However they are not here, which is causing the effects of these tools to be broken.
=> fixed broken rusted shield and rusted sword

src/tcgwars/logic/impl/gen7/GuardiansRising.groovy
Fixes https://forum.tcgone.net/t/bug-report-tapu-koko-gx-gri-153-was-able-to-use-aero/976
=> GRI47: Switch only if energy moved

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy, src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen3/UnseenForces.groovy, src/tcgwars/logic/impl/gen4/Arceus.groovy, src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen4/Platinum.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy, src/tcgwars/logic/impl/gen4/Stormfront.groovy, src/tcgwars/logic/impl/gen4/SupremeVictors.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/DragonMajesty.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/GuardiansRising.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen7/SunMoon.groovy, src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy, src/tcgwars/logic/impl/gen8/ChampionsPath.groovy, src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy, src/tcgwars/logic/impl/gen8/LegendaryHeartbeat.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy, src/tcgwars/logic/impl/gen8/SwordShieldPromos.groovy
See #dev channel in the discord server. Currently effects that trigger when a Pokémon is damaged by an attack are activated before the damage and effects of that attack are applied. 
This is problematic if for example an attack heals the attacking Pokémon, that effect should resolve before an effect of an Ability that places damage on the attacking Pokémon. With the current implementation, a Pokémon with previously zero damage would be able to immediately heal the damage it shouldn't yet have during the resolution of the attack effect. Another relevant example is when an attack that discards an Energy faces against a triggered effect that sends back an Energy to the hand. The attacking player should choose the discard first, and only after that the defending players makes the choice on …
=> Fix timing of effects that trigger when pokemon is damaged by an attack

src/tcgwars/logic/impl/gen7/UltraPrism.groovy
If there are no more M energy in the discard pile this card would
display the player's Pokémon to choose from that would have to be
clicked through to finish the attack. Instead, this will now just
skip any remaining checks if the discard pile no longer has any M
energy in it.
This should "fix" https://forum.tcgone.net/t/bug-report-solgaleo-prism-star-upr-89-attempting-to-u/2163
=> UPR89: Don't show useless dialog to click through

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy, src/tcgwars/logic/impl/gen7/LostThunder.groovy, src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
Minor fixes and optimizations
-Effects that return a pokemon to your hand no longer cause payback effects to crash the game
- discardDefendingEnergyAfterDamage now lets the attacking player select the energy instead 
- Lanturn's Energy Grounding allows the player who owns lanturn to select which energy is moved
- Zacian V allows you to select metal energies the first time it shows you your top 3 cards
- LOT beautifly only hits for 30 damage instead of 100 (kinda want to leave this one in)
- Desert Geyser is no longer spelled Desert Geizer
=> Retooled bugfixes2

src/tcgwars/logic/impl/gen8/BattleStyles.groovy
Went with a different approach than is usually used. Hoping this fixes most cases where using your own ability on the Pokémon doesn't trigger the ability.
=> Corv vmax bst110

src/tcgwars/logic/impl/gen8/BattleStyles.groovy
Invert the check that was originally used. Check if an ability being used
is from Corviknight's player, if so, explicitly allow it, else block.
=> BST110: Invert original ability check

src/tcgwars/logic/impl/gen7/BurningShadows.groovy
Whoops. Seems to be the only metrnomeA I messed up, but could be others.
=> BUS:80 Should only copy Basic Pokémon moves

src/tcgwars/logic/impl/gen1/BaseSetNG.groovy
Giovanni's Magikarp seems to have had the only correct
implementation which has been adapted slightly and used for all of
the relevant effects
Should fix https://forum.tcgone.net/t/bug-report-farfetchd-bs-27-farfetdh-d-used-leek-slap-twice/2326
=> Can’t use attack again as long as still in play fixes

src/tcgwars/logic/util/CardList.groovy
Add documentation to CardList's moveTo method.
Mainly using this to force a rebuild.
=> CardList: Add moveTo documentation

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen1/TeamRocketNG.groovy, src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy, src/tcgwars/logic/impl/gen4/RisingRivals.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy, src/tcgwars/logic/impl/gen7/CelestialStorm.groovy, src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen7/UltraPrism.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
Q. Spinda has a Rainbow Energy attached, which counts as every type of energy, and uses its "Synchro Removal" attack. Can it discard a Call Energy from the defending Luxray [GL]?
A. Yes, Call Energy may be discarded by this attack, because the types of energy attached to Spinda includes colorless, the same type as that of Call Energy. (Sep 3, 2009 PUI Rules Team)
=> Add C to Energy cards that provide energy of Every type

src/tcgwars/logic/impl/gen4/GreatEncounters.groovy, src/tcgwars/logic/impl/gen4/Unleashed.groovy
Based on a ruling for Combusken, should just increase damage (and not place an effect on the defending Pokémon, even if wording on the card is confusing)
=> Fix "Bulk Up" in Combusken (GE) and Lucario (UL)

src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy, src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
* Luxray (Legends Awakened)'s Poké-Body "Rivalry" should increase damage by 50, not 30.
* Politoed (Legends Awakened)'s Poké-Body "Enthusiasm" should only work when a Poliwag, a Poliwhirl and a Poliwrath are in play (not counting pre-evolution of evolved Pokémon in this). The damage increase should also not be ignored by shred attacks, should they happen.
* Rayquaza (EX Deoxys) should now stop causing a NPE when using it's "Dragon Aura" Poké-Body.
* EXP.ALL (EX FireRed & LeafGreen) should in theory prevent activation when a benched Pokémon is KO'd (couldn't reproduce, but logic could be improved anyway)
* Sidney's Stadium (EX Power Keepers) should now properly remove pre-existing Special Conditions.
=> Card Fixes

src/tcgwars/logic/impl/gen3/Deoxys.groovy
Should only check for basic Energy cards, not any. This should fix some issues with it regarding this ability.
=> Fix "Dragon Aura" in Rayquaza (DX)

src/tcgwars/logic/impl/gen4/DiamondPearl.groovy, src/tcgwars/logic/impl/gen4/GreatEncounters.groovy, src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy, src/tcgwars/logic/impl/gen4/MajesticDawn.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy
* General fixes
- Added/corrected some Weaknesses and Resistances from several cards, matching them to the values printed in the cards.
* Legends Awakened
- Politoed check for Enthusiasm should now work properly (and in a more efficient way).
* Secret Wonders
- Team Galactic's Mars should now be playable even if the opponent has no hand. A check is now done in order to avoid doing that part of the card's effect were that the case (having at least 1 card in your deck is still a requirement).
- Fixed some instances of `Source.POKEBODY` being mispelt as `Source.POKBODY`. Affects Ludicolo, Ampharos, Flygon and Magmortar.
* Great Encounters
- Sceptile should now apply its "Wild Growth" Poké-Body to Grass type Pokémon only.
- Caterpie should only be able to use "Pupate" when in the Active Spot. …
=> Some DP-era card fixes

src/tcgwars/logic/card/Collection.java, src/tcgwars/logic/impl/gen3/PopSeries4.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy, src/tcgwars/logic/impl/gen3/RubySapphireNG.groovy
* Relocated some cards already implemented in Groovy, and redirected to the RubySapphireNG print. Affects:
- Blaziken (RS 3, PK 5)
- Delcatty (RS 5, PK 8)
- Gardevoir (RS 7, PK 9)
- Slaking (RS 12, PK 13)
- Sceptile (RS 20, POP4 5)
* Besides that, this PR implements cards 1 through 22.
=> Groovy re-implementation for "Ruby & Sapphire - Base Set" (Cards 1-22)

src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy, src/tcgwars/logic/impl/gen3/Emerald.groovy, src/tcgwars/logic/impl/gen3/PowerKeepers.groovy, src/tcgwars/logic/impl/gen4/Platinum.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy
- Cacturne-ex (Emerald) and Dusclops (Crystal Guardians) should now properly block attaching Special Energy other than [D]/[M] Energy to the opponent's Active Pokémon when in the Active Position.
- Blaziken (Emerald) should now ask for Fire energy instead of Fighting energy for its "Damage Burn" attack.
- Sceptile (Emerald) should no longer cause an Engine Error when removing special conditions (also changed said effect's source from SRC_ABILITY to POKEBODY)
- Carvanha (Power Keepers) and Sharpedo (Secret Wonders) should now apply Poke-Body-sourced damage with their "Rough Skin" Poke-Body.
- Houndoom G (Platinum) should now only ask about discarding a [D] Energy for extra damage when attacking with "Dark Slash" if any [D] Energy is actually attached to them.
=> Some EX/DP Era fixes (EM, CG, PK, SW, PL)

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen4/DiamondPearl.groovy, src/tcgwars/logic/impl/gen4/GreatEncounters.groovy, src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy, src/tcgwars/logic/impl/gen4/MajesticDawn.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen4/Platinum.groovy, src/tcgwars/logic/impl/gen4/PopSeries6.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy, src/tcgwars/logic/impl/gen8/RebelClash.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
- Mothim (Majestic Dawn) should now properly calculate its attack damage based on each type of Wormadam its owner has in play. Crystal Shard interaction should also work correctly now.
- Quick Ball (Mysterious Treasures, Majestic Dawn) should no longer shuffle the deck if the first card revealed is a Pokémon card (since there's no "other revealed cards" in that instance).
- Flaaffy (Platinum) should now be able to properly evolve from a Mareep.
- Monferno (Platinum) should now have the correct attack cost for "Fire Tail Slap" ([R] instead of [R][R])
- Dialga and Palkia (both Great Encounters) should now work as copies of their original DP-Base Set prints. This should work some issues with the GE prints.
- Palkia (DP-Base Set, reprint in Great Encounters) should now use a targeted effect …
=> HP-MD related fixes, fix for Noctowl (SSH)

src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy
* Ninjask (Legends Awakened) should now do 30 damage when using "Chip Off".
* Banette (Secret Wonders) should now only prevent attacking with Ghost Head when at 10HP (which is when no damage counters would be placeable at all)
* Kyogre (Legends Awakened) now uses the `attachEnergyFrom` static (taken from the implementation for Cosmic Eclipse's Groudon), and no longer heals based on the energy attached via this attack.
=> Some more 2008 format related fixes

src/tcgwars/logic/impl/gen8/ChillingReign.groovy
Expected Behavior:
When Gengar's knocked out from damage by opposing pkmn, owner of Gengar selects up to 2 cards from deck and adds to hand
What's actually happening:
When Gengar's knocked out from damage by opposing pkmn, **opponent of** owner of Gengar selects up to 2 cards from deck and adds to **opponent's** hand
=> Fix Gengar_57 CRE Last Gift

src/tcgwars/logic/groovy/TcgStatics.groovy, src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy, src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy, src/tcgwars/logic/impl/gen4/GreatEncounters.groovy, src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy, src/tcgwars/logic/impl/gen4/MajesticDawn.groovy, src/tcgwars/logic/impl/gen4/Platinum.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy, src/tcgwars/logic/impl/gen4/SupremeVictors.groovy
This should allow Alakazam (Mysterious Treasures) "Power Cancel" and Power Spray to effectively block these powers, while still ending the owner's turn (as intended, and clarified through erratas in earlier cards from the block).
Affected cards by this:
- Swampert-ex (Crystal Guardians)
- Latias-ex δ (Dragon Frontiers)
- Blastoise (Secret Wonders)
- Dialga Lv.X (Great Encounters) 
+ _Not affected by Power Spray, but can make use of this static._
- Call Energy (Majestic Dawn)
+ _No use of the static, but a bc message was added based on it._
- Unown V (Legends Awakened)
- Ludicolo (Platinum)
- Electivire E4 Lv.X (Supreme Victors)
+ _Just a TODO, not yet implemented._
Co-dependant on https://github.com/axpendix/tcgone/pull/179
=> Add "usingThisAbilityEndsTurn" static, make use of it in DP cards with turn-ending Poké-Powers

src/tcgwars/logic/impl/gen8/ChillingReign.groovy
Replace incorrectly named ability prompt for "Quick Shooter" with "Quick Shooting"
=> Update Chilling Reign Inteleon prompt text

src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy, src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy, src/tcgwars/logic/impl/gen3/LegendMaker.groovy
This should've been commited through a PR to master, then merged individually into pre-rpc. My bad on that, shouldn't happen in the future.
Summary of the merged fixes:
* Fix "Family Bonds" Poké-Body in Nidoqueen (FRLG 9)
- Use getterA instead of delayedA, so it stops when the PCS leaves play.
* Fix Nidoran Female (FRLG 70)
* Fix Memory Berry (CG 80)
- Only check moves for self
* Fix "Speed Stroke" in Aerodactyl (LM 1)
- Should no longer prevent effects from ex Pokémon
=> Merge some card fixes from the pre-rpc branch

src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy
Prior to this update Celebi star was placed at bottom of opponent's deck, then magically appeared on the owner's bench for some reason. This code copies Aipom's Snappy Move pokepower and should function properly.
=> Fixed Celebi Star

src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy, src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy, src/tcgwars/logic/impl/gen8/SwordShield.groovy
* Jynx (Unified Minds 76) and Gengar (Sword & Shield 85) should now properly move damage counters (using directDamage instead of modifying the health directly, so it can be partially prevented). Jynx will also now exclude the source Pokémon from the list of potential targets for the counter being moved.
* Celebi Star (Crystal Guardians 100) should now do everything intended prior to preventing the Knockout.
=> Corrections for July 23rd's fixes

src/tcgwars/logic/impl/gen4/Arceus.groovy, src/tcgwars/logic/impl/gen4/DiamondPearlPromos.groovy, src/tcgwars/logic/impl/gen4/GreatEncounters.groovy, src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy, src/tcgwars/logic/impl/gen4/MajesticDawn.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen4/Platinum.groovy, src/tcgwars/logic/impl/gen4/RisingRivals.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy, src/tcgwars/logic/impl/gen4/Stormfront.groovy, src/tcgwars/logic/impl/gen4/SupremeVictors.groovy, src/tcgwars/logic/impl/gen4/Triumphant.groovy, src/tcgwars/logic/impl/gen4/Undaunted.groovy
This PR depends on https://github.com/axpendix/tcgone/pull/214
Requires https://github.com/axpendix/tcgone/pull/214 to be merged first.
* Rework confusion boost for Aromatisse (BKT 106) and Grumpig (LA 56)
- Now it should use the same override for confusion damage in both attacks, as only one would apply (since it's an override, 6 instead of 3).
* Implement "Mend" on Lairon (Mysterious Treasures 53)
- Added some logic for making the heal conditional.
* Further fix Lairon (Mysterious Treasures 53)
- Should now heal 2 damage counters instead of only 1.
* Partial Fix for Porygon-Z (DP Promo DP35) and Fix for Level Max (PL 107)
- "Learning" and "Level Max" should no longer allow leveling up a Leveled-Up pokémon.
* Fix Defender (Undaunted 72)
- Should now be applied after W&R, not before.
* …
=> End of July batch of fixes (mostly gen 4 related)

src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy, src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy, src/tcgwars/logic/impl/gen4/DiamondPearlPromos.groovy, src/tcgwars/logic/impl/gen4/GreatEncounters.groovy, src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy, src/tcgwars/logic/impl/gen8/ChillingReign.groovy
Was trying to compare a player with a Pokémon. Kinda sus. This affected Feraligatr Delta (Dragon Frontiers 2), Gyarados Delta (Holon Phantoms 8), Darkrai (DP Promo DP52), Darkrai Lv.X (Great Encounters 104), Diancie Prism Star (Forbidden Light 74) and Cinderace (Chilling Reign 28).
=> Fix several cards with incorrect attack checks (it.to -> it.to.owner)

src/tcgwars/logic/impl/gen3/PokeParkForest.groovy
Card implementations for PokePark Forest.
PokePark's Latias's Mist Ball may require a different function since it discards 2 colors of Energy. Reuse the one on Latias ex DR 93's Mist Ball or Dragonite ex DR 90's Dragon Wave.
=> PokéPark Forest

src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy, src/tcgwars/logic/impl/gen4/MajesticDawn.groovy, src/tcgwars/logic/impl/gen4/Triumphant.groovy
Included the Gen4 mons because I have no idea if they have to interact and wanted to be safe. There are a SuMo card and SwSh card that would also interact with this in unlimited format, but I just didn't include them. Could though.
=> Concept for handling Energy Rain

src/tcgwars/logic/impl/gen4/GreatEncounters.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen4/RisingRivals.groovy, src/tcgwars/logic/impl/gen4/SecretWonders.groovy
Some Gen 4 Pokémon incorrectly use "Evolved Pokémon" to refer to Evolution Pokémon. Only a few of them received official errata (the ones that refer to Stage 2s, i.e. Alakazam MT, Glalie MT, Staraptor SF).
Two of them (Dodrio MT and Flygon RR) have rulings on the Japanese FAQ page to confirm that they refer to Evolution Pokémon. This PR fixes those two, plus any others that don't have Japanese rulings, but use identical wording.
More info [here](https://docs.google.com/document/d/1T3YmOaQ2Dhv_Lc_dRXsglv27qzsSShnJOYOwDuOKeL0/pub).
=> Evolution Pokémon

src/tcgwars/logic/impl/gen3/Deoxys.groovy, src/tcgwars/logic/impl/gen4/DiamondPearl.groovy, src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy, src/tcgwars/logic/impl/gen4/Stormfront.groovy
Changed Crystal Shard and Raichu LV.X to check before `PROCESS_ATTACK_EFFECTS` instead of `ATTACK_MAIN`, based on Memory Berry CG's implementation. This should make them work properly if an unusable attack is chosen.
=> May 2025 fixes

src/tcgwars/logic/impl/gen4/Platinum.groovy
Cyrus’s Conspiracy is able to search out any item when it should only be able to search out items that have Team Galactic’s Invention in their name. I would assume this is because the code says that it has to be either an item or Team Galactic’s Invention when it should be both. This also applies to Honchkrow's Honcho’s Command.
https://forum.tcgone.net/t/br-cyruss-conspiracy-pl-105-premier-ball-sf-91-cyrus-conspiracy-allows-you/16960
=> Fix Team Galactic’s Invention search
