axpendix/tcgone-engine-contrib

- src/tcgwars/logic/impl/gen4/HeartgoldSoulsilver.groovy
- src/tcgwars/logic/impl/gen4/HeartgoldSoulsilverPromos.groovy
- src/tcgwars/logic/impl/gen4/Triumphant.groovy
- src/tcgwars/logic/impl/gen4/Undaunted.groovy
- src/tcgwars/logic/impl/gen4/Unleashed.groovy
Removed "Prime" from the card names to match rulings and actual game play
> Fix prime names

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
This PR will hopefully resolve some of the issues with the code not being able to build on KissCI
> Fix Unified Minds CI

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
This is the second PR to fix the bugs in the UNM set.  This addresses a subset of the issues found so far.
This PR includes the fixes for the following:
- STUNFISK_67 Trap Bolt
- ESPEON_DEOXYS_GX_72 Psychic Club
-  ZYGARDE_124 Boost Fang
- LATIOS_GX_78 Power Bind ability
- TERRAKION_122 Cavern Counter
- Evolution path for SILVALLY_184
> Fix Unified Mind Bugs

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
The fixes include:
- Fix for GARCHOMP_GIRATINA_GX_146 GG End Gx
- Implement U_TURN_BOARD_211
- Fix text for Giant Hearth stadium
- Fix evolution paths for anything evolving from Unidentified Fossil
> More Unified Mind Fixes

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Fixes include:
- Fix ARAQUANID_49 Sticky Web
- Fix ESPEON_DEOXYS_GX_72 Cross Division GX
- Fix GARCHOMP_GIRATINA_GX_146 GG End GX
- Fix SLUMBERING_FOREST_207 stadium
- Fix GIRATINA_86 Dimension Breach ability
> Fix unified minds bugs

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
This is a concept I was hoping to work around. I am not sure if it works but in theory, it should.
https://github.com/TTTrainer/tcgone-engine-contrib/commits?author=TTTrainer
> Uxie Patch

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Changes include:
- Implement POKEMON_RESEARCH_LAB_205 stadium
- Add JIRACHI_GX_79 implementation for Psychic Zone ability
> Unified Mind Fixes

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Includes a missing closing bracket
> UNM Fixes for CI

- src/tcgwars/logic/util/EvolutionChains.java
ADD("Unidentified Fossil", "Archen", "Archeops");
ADD("Unidentified Fossil", "Tirtouga", "Carracosta");
> rare candy missing evolution line add

- src/tcgwars/logic/impl/gen7/HiddenFates.groovy
This includes the template for Hidden Fates without any implementation for moves/abilities that are new.
> Initial Hidden Fates template file

- src/tcgwars/logic/impl/gen7/HiddenFates.groovy
This PR includes work for nearly all the Pokemon and some of the Trainer cards.
I've added a //TODO: tag for the ones that still need work.
> Initial Hidden Fates Implementation

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
> cryogonal fix missing damage

- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
> eevee gx promo fix hp

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
This PR introduces an implementation for most of the Cosmic Eclipse set.  More to come.
> Add Initial Implementation for Cosmic Eclipse 

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
> Fix Cosmic Eclipse build

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
> Fix CEC Build Errors

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
This PR introduces more Pokemon and Trainer cards implementations.
> Implement more cards

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Ultra beast editions and other fixes
> Cosmic Eclipse Implementations

- src/tcgwars/logic/impl/gen8/SwordShield.groovy
First PR, lemme know if I got something wrong
> Clearing out some tiny redundancies

- src/tcgwars/logic/impl/gen8/SwordShield.groovy
added +120 damage to second attack when opp's active is asleep
> fix MUSHARNA_88

- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
This should catch all the redundancies I missed in my original PR. Surprised to see I missed them >.<
> Sun and Moon promo cleanup (redundancies / empty space)

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
I did a big dumb lastDamage has to be defined :(
> Fixed counter

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
My last shot at this before I admit I dont really understand what is going wrong:P
> Fix pidove(again)

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Now with fewer game engine errors!
> reverted changes to pidove

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Im not even gonna try touching its ability D:
> Fixed lombre’s attack

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
one of these days ill just download a java ide
> Fixed flapple

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
> Update to English localizations + Fix Magmortar

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Thank god im not the only one to make typos
> Fixed cinderace VMAX

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
There is no Galarian Koffing in the set, it does evolve specifically from Koffing.
> Revert Galarian Weezing evo change + Perrserker redundancy

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Secret Rare Perrserker was missing "Galarian" from it's name and Big Charm was named Giant Charm.
> Fix Rebel Clash card names

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Not sure if this will work, its worth a shot tho
> Bandaid sirfetch’d

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Im assuming it was a translation error
> Fixed sigilyph

- src/tcgwars/logic/impl/gen7/LostThunder.groovy
https://forum.tcgone.net/t/br-wait-and-see-hammer-lot-192-if-opp-has-no-energy-game-ju/9695?u=mt.gufo
Bug report fix
> Added a check to wait and see hammer_192

- src/tcgwars/logic/impl/gen8/SwordShield.groovy
https://forum.tcgone.net/t/br-galarian-linoone-ssh-118-trevenant-dusknoir-gx-smp-21/9699?u=mt.gufo
> Fixed Galarian Linoone

- src/tcgwars/logic/impl/gen7/DetectivePikachu.groovy
Prize cards work in a different way than I expected them to
> Refixed Mr_Mime

- src/tcgwars/logic/impl/gen7/DetectivePikachu.groovy
Only allow selection of face down cards
> Mr Mime changes

- src/tcgwars/logic/impl/gen7/LostThunder.groovy
- src/tcgwars/logic/impl/gen8/SwordShield.groovy
Both had the same bug as heatran GX
> Fixed cinderace and xernias prism star

- src/tcgwars/logic/impl/gen7/TeamUp.groovy
Altered code from teamup articuno
> Another try at scoop up block

- src/tcgwars/logic/impl/gen7/TeamUp.groovy
> Mr_Mime_66

- src/tcgwars/logic/impl/gen7/TeamUp.groovy
Added all the Scoop Up trainers I could think of
> Scoop Up Block

- src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy
https://forum.tcgone.net/t/br-tangrowth-unb-17-whenever-i-use-tangrowths-attack-the-g/9716?u=mt.gufo
> Fixed Tangrowth’s Chlorowhip attack

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Probably isn’t going to work but maybe a jumping off point?
Changed the order of checks to see if the other parts worked
> My shot at to entry

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Fixing what caused top entry to crash last time I tested
> Top Entry Edits

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Switched away from using my with new understanding of how thisCard works
> Top-Entry testing

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Still isnt going to work but maybe Ill find out why?
> Fixed build

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Not sure how thisCard.player works so testing different ways to code a turn check
> Top Entry turn confirmation

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
I thought I fixed this the last time 
should work now
> Nugget fix

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
After all that I forgot to add back prevent. Targeted draws work fine tho
> Nugget Final

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Never again will assert false be found in the code(at least I hope)
> Nugget fix final(final)

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Untitled_12_updated_final_final.txt.jpg
> Nugget is now implemented

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Im unclear how energy costs are stored so this is my first shot
> Ninetales V test

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Energy notation used in special energy
> Ninetales_V

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Learning how getters function and the difference between a getterA and a getter
> Ninetales V

- src/tcgwars/logic/impl/gen8/SwordShield.groovy
Shouldn’t crash the game anymore
> Galarian Stunfisk

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
No longer asks the opponent if they want to use top entry
> Top entry fix

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Please dont merge untill after v44.3 goes live
> Mimikyu Fix

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
- src/tcgwars/logic/impl/gen8/SwordShield.groovy
Some attacks aren't necessarily badly worded or difficult to understand, however I think it'd help with understanding and look cleaner generally if there were a more consistent writing style to attack/ability functions. This is an attempt to do this for Sword and Shield and Rebel Clash.
Please comment on any syntax error, grammatical errors, or general comments regarding my changes if something is too lengthy or unclear.
I do plan to look over older sets as well.
> Re-write Attacks/Abilities from SSH/RCL

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
https://forum.tcgone.net/t/br-steelix-cec-139-if-theres-no-pokemon-with-retreat-cost-4/9757?u=mt.gufo
> Added attack requirement to steelix

- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
Only prevents effects of attacks to itsself on GX
> Jolteon GX

- src/tcgwars/logic/impl/gen7/BurningShadows.groovy
This should allow scoop up block to function properly
> Added targeted param to acerola

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Changed debug incase it was screwing with the move. Messages didnt seem to happen even though the move activated
> Sunflora debugging

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Not dealing with unregistering the effect yet.
> Sunflora idea test

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Because who wants infinite sunflowers?
> Sunflora infinite fixed

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Using an attack now ends the turn and the dialog was fixed.
> Sunflora fixs

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
If this works next commit will fix ttgx bug and unregister the effect
> Sunflora test

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
I know I said I would implement unregister but the last broke OK??? IM SORRY!
> Sunflora fix

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Same idea to #208. Please verify if there is any out of date code, I made this branch a week ago I think. I tried to put in the changes from master manually but may have made a mistake.
Please comment if any grammar appears wrong, redundant, or similar.
> Cosmic Eclipse clearup

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Same implementation as sunflora
> Jolteon Speed Cheer fix

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Added poison is 9 so total is 10
> Dragalage_92 adds proper poison

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
> Aerodactyl_1

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Restructured Grimsley to allow for moving of up to 3 damage counters
> Grimsley up to 3 counters

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Change to proper for loop from n.times
> Change Grimsley loop

- src/tcgwars/logic/impl/gen7/TeamUp.groovy
> Metal goggles

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
forgot that it can only activate once per turn
> Oricorio gx final fix

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Ability now tracks kos even before it is on the field
> Oricorio Gx

- src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy
Addapted from wobbufett from burning shadows
> Aggron ability

- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
> Altaria Ex

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Should prevent damage from all attacks not just attacks from the defending pokemon
> Cosmeom attack fix

- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
Every day I learn something new about how checks work
> Altaria stage 2 check

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
fossil will now be ability blocked properly
> Changed fossil abilities

- src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy
I found what I was looking for. Turns out it was a capital letter on a P and a B. I is the big dumb
> Fix aggron

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Fixed so it properly attaches to any of your pokemon instead of just your benched
> Fix Kyogre 53 CEC

- src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy
Fix so it can no longer attach energies to EX pokemon
> Fix Electrode EX FRLG 107

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Can attack even if no benched pokemon have damage counters.
> Decidueye_20

- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
Ive fixed this twice now. Is there a missing import or something that would allow the unaltered code to work properly?
> Cloyster delta Ability fix

- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
> Added null check so game doesn’t crash

- src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy
> Fix celesteela effect

- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
There is probably a better way to convert from a card list of one card to exactly that card but this way works.
> Charizard star delta

- src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy
Allows multiple activations of different peal of thunders
> Charizard delta 4

- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
It is really messy tracking holon supporters via a global ability.
> chimecho delta

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
I give myself 50/50 for this not breaking the build.
> Delcatty_4

- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
Fixed Jolteon GX to properly prevent effects for the next turn only
> Fix Jolteon GX SMP 173

- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
- src/tcgwars/logic/impl/gen3/UnseenForces.groovy
Testing multiple commits in a pr
> Meganium 9 and Flygon delta 7

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
If this works properly I will implement devolving also
> Full_Flame ability implementation

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
> Boss’s orders fix

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
Another way it could work but more guesswork
> Full Flame

- src/tcgwars/logic/impl/gen7/DragonMajesty.groovy
Found this randomly using dev ui
> Combusken_5

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
> Fix Copperajah V RCL 136

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
I hope that lists can be stored objects
> Vaporeon_42

- src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
fixed scope of eff I think I made every possible error implementing this
> Glacia’s stadium

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
more tweaks and debugging. This card should have worked properly 3 commits ago
> vaporeon 42

- src/tcgwars/logic/impl/gen8/SwordShieldPromos.groovy
I'm curious if anything will be wrong since carddb-tools was used to generate this. There was issues when I did this with Shiny Vault last time so, lemme know if there are any.
All cards are implemented except Polteageist V. The ability is out of my scope to code, but I got all the simple mons >.<
> Initial Sword and Shield Promos

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
addid ) to test case and added _ to names
> Vaporeon 42 debugging

- src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy
Now ends the turn when the effect is triggered
> Holon Circle

- src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
Please work I pray to you oh Rubberus Duckyus, god of compilers, creator and destroyer of hello worlds, that this pr 333 might stand for longer than a few minutes.
> Holon Energy GL

- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
Now with more comments. God forbid I document anything I do.
> Holon’s Castform step 1

- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
added energy check and nothing else at all ;)
> Holon’s castform

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Now has you choose the controler of the pokemon you want to remove a tool from.
> Tool Scrapper qol fix

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
> Tool Scrapper qol

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Allows the player to backtrack out of their decisions and stop more easily
> Tool scrapper qol extended

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
I knew it was too good to be true that making a change wouldn’t break the build
> tool scrapper qol ++

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
The pokebody now works on both active pokemon
> Misdreavus 40

- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
Fix hang if no acceptable pokemon in hand
> Holon fossil

- src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
Tracks if the card was played from hand and fixes crash
> Umbreon delta

- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
using typing to determine whether it is a bug with type comparison or something different
> mew * testing

- src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
not sure if this will work or not but worth a shot
> Kabutops_10

- src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
code works, added a from hand check, removed redundant if,
> Kabutops 10

- src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy
stole my implementation from vaporeon_42:cec
> Sceptile ex delta

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
stole code from tcgstatics and am not entirely sure what it does. Literally have never seen playertype before
> Top entry confirm targeting

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
checks abilities after every card is played. Ideally I would hook after benchPCS but I don’t know how to do that. I also considere PLAY_BASIC_POKEMON but I think that only triggers on playing the card. Cards like nest ball would dodge the check.
> Solrock_25

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
Shouldn’t crash the game but im working with code I dont understand
> Solrock_25 check

- src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
> azurill 20

- src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
> Holon Tower

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
instead of the types of the top card. This should work
> Mew uses types of pokemon

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
Im just guessing keywords that would make sense. Resistances are slightly more complex than types as they hold both a type and a value.
> Possible armaldo ex fix

- src/tcgwars/logic/util/PokemonCardSet.java
I hope Im allowed to touch these. I think I can implement ampheros delta here.
> Added hasPokePower and hasPokeBody

- src/tcgwars/logic/util/PokemonCardSet.java
Turns out I dont know what im doing outside of impl
> Revert "Added hasPokePower and hasPokeBody"

- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
I wish we could change these but we cant :(
> Unfix card ids.

- src/tcgwars/logic/util/PokemonCardSet.java
I know there are redundant imports. I plan on deleting them one at a time until I figure out which ones I actually need.
> Retry hasPokePower +

- src/tcgwars/logic/util/PokemonCardSet.java
> added hasPokePower++

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
Leaving comment as this is just an attempt. May need to revert, but if this works I'll remove comment when I add the functionality to the other "mark as basic" cards.
> Strange Cave: attempt at marking as basic

- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
- src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
Remaining cards that require the ability to mark as basic since the testing with Strange Cave seemed to have worked properly.
> Mark as basic

- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
- src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
I'll have to give this another look later.
> Revert failed attempts

- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
More logic than I would have liked but less logic than I expected.
> Holon Veil

- src/tcgwars/logic/impl/gen7/TeamUp.groovy
Added deck shuffle after ability use
> Fix Alolan muk TEU 84

- src/tcgwars/logic/util/PokemonCardSet.java
> Added isPokemonDelta

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Now counts knockouts by sources other than damage
> Rosa Ko detection

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
The fix worked but shouldn’t be used. Ill have to do more testing
> Reverted Vortex Chop fix

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Perfection shouldn’t add duplicate moves to Mew3
> Optimized Perfection

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Added debug messages and a test list to see what went wrong with my last commit. I intend to revert this but hopefully I can get a better understanding of how the code works.
> Testing lists holding moves

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
Huzzah it works and I didn’t even know it
> Optimized Perfection ability

- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
At least I hope this does. If it doesn’t im scared.
> Fix perfection for discard

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
- src/tcgwars/logic/impl/pokemod/PokemodBaseSet2.groovy
Dugtrio was numbered incorrectly. I fixed this but am not sure what else needs to get fixed to avoid further issues.
Mr Mime had a similar issue. Initially named MR__MIME_27 now named MR_MIME_27
Farfetch’d name was changed in PokemodBaseSet
Growlithe’s attack was changed per the request of the pokemoddev discord channel
Pidgeot had the effect from hurricane removed :( BigSad
> PokemodBaseSet2 7-130

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
Coded it so that pokemod would have no dependencies on non-pokemod sets. I hope we can keep this tradition.
> Double Colorless Energy

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
Implemented Leek Slap
Easier than sirfetch’d because why not?
> PokemodBaseSet 27

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
Im totally not doing an easy fix trying to cover up my assert mistake on farfetch’d
> Pokedex_87

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
Also added a missing TODO for a fossil with the missing "treat this benched Pokémon as a Basic Pokémon" implementation.
> Implemented Dialga (DP 1)'s attack effect

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
I cant wait for a world where scoop up block interacts with pokemod but when it does, scoop up will be ready.
> Scoop up attempt

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
I'm not sure if the text corrections are overkill. There also seem to be weird apostrophes abound in the existing text that I didn't notice prior. I can PR just the Flapple fix if that is preferred.
> Fix Flapple RCL 22 Apple Drop Ability + RCL Grass Type Card Text Corrections

- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
> Tyranitar ex delta

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
Do farfetch’d in a better way and fixed bug with scoop up
> PokemodBaseSet fixs

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
- src/tcgwars/logic/impl/gen4/GreatEncounters.groovy
- src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy
Electivire (DP 3) is partially implemented, missing a way to check for Elekid as a pre-evolution. This will be needed for multiple cards in this set and future ones. **(Edit: Testing a potential solution on Roserade, just added to the PR)**
Dialga (DP 1) should now return all energy properly. And Magnezone (DP 8) should be able to evolve (had Magneton*e* as its pre-evolution)
Also Fixed Huntail (GE 42) and Milotic (CIN 27).
> DP: Fixed Dialga (1), Implemented 2-50

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
Since when could you not move a specific card? I guess ill use a card list of just that card instead.
> Scoop up fixs

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
get(0) always returns the top pokemon card. I just hope this doesn’t break with pokemon cards turned into other cards like clefkey or electrode.
> Another shot at scoop up + Implementing more cards

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
- src/tcgwars/logic/impl/gen7/DragonMajesty.groovy
Hopefully with this they'll work properly.
> Mallow & Lana and Switch Raft

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Also adds powerUsed to Sigilyph when its ability is used.
Pushing this now since it's definitely too late to keep on looking through code right this second.
> Galarian Sirfetch'd RCL 95 - Attempt to restore Meteor Assault effect properly

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
defender and plus power are hard.
> Implemented pokemod trainers

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
pokemonEX refers to EX pokemon. EX refers to ex pokemon
> Pokemod EX checks updated

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Only Trainer and Energy cards left to double check.
> More RCL Pokemon Bugfixes

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
Harder than expected with the nonstandard no weakness,resistance,or effects.
> Implement Charizard EX burn down

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
TIL playertype just refers to player a or player b. thisCard.player returns a playerType
> Top Entry confirm fix

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
* Hopefully Noctowl 34 now works? Missing the proper target for "putting prize face up"
* Wobbuffet 41 will work as it should (avoiding anti-heal), but won't be blocked by stuff like metal goggles yet.
As of rn Empoleon Lv.X is an evolution, this needs to be corrected as it's meant to be a "level up" card (considered as "Empoleon" name-wise)
> DP: Implemented 51-120, Fix Attempts for 34 & 41

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
Aight let's try the id instead, that's something the initializer should take right?
> Second attempt at Empoleon Lv.X fix

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
Ok this one's on me, forgot to refactor a line
> One more fix for Empoleon Lv.X

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
This one's on me II: Electric Refactoroo
> Empoleon Lv.X

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
One last attempt for tonight...
> Empoleon Lv:X

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
If it works fine here, will update EX-era babies to use the same calls.
> DP: Baby Evolution modularization

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
Thanks on prev commit to flagrama <3
> Empoleon Lv.X: Is this it?

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
> More work on Empoleon Lv. X and Speed Stadium

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
> Empoleon Lv. X reworked

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Fossil Excavator (111) might take a bit while thinking how to implement it in proper (Also wanna confirm the card text being correct, the Stage 2 part even on japanese sounds odd).
> Initial Work on Mysterious Treasures (109-110,112-124)

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
See if it actually works, or it also breaks like wager.
> Re-Enable Fossil Researcher

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
This reverts commit 259b4485de6eb4a7e8739024a3391bef99c2aeff.
> Revert "Re-Enable Fossil Researcher"

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Wager still using flip, but done from scratch. Electivire shouldn't break when checking now.
> MT: Team Galactic's Wager (115) Rewrite, Electivire Lv.X (121) fix, first berry implementation

- src/tcgwars/logic/groovy/TcgStatics.groovy
Not implemented on any card yet, just a check to see if it crashes now.
> Readded RPS to statics

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
* Implemented R-P-S back in Team Galactic's Wafer (115)
* Fixed a typo in Electivire Lv.X (121)
* Fossil Excavator (111) fix attempt
> MT: R-P-S readded to card, fixed a typo and fix attempt at Fossil Excavator.

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Just to check if Excavator works
> Rolled back RPS on Wager

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
See if this is what triggers the errors.
> Debug commenting

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Will rebuild Excavator from scratch, worked for Wager...
> Nuked Fossil Researcher, added temp debug code

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Feeling like vazkii vs scala.arrays rn with flip...
> Fixed typo

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Let's see if these are the ones breaking the build
> Fossil Excavator Part 1: Adding defs

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
If this doesn't build, feel free to revert it until I wake up and take another look at it lol
> Fossil Excavator Part 2: Requirements

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Should simplify this whole situation.
> Moved isValidFossilCard to statics

- src/tcgwars/logic/impl/gen4/MajesticDawn.groovy
> Implemented Dialga 4's Adamant Orb held item

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
> MT: Fossil Excavator (111) [hopefully] Final fix

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
TODO:
* Write the check for Vigoroth (68) to increase the damage in "Wake-Up Punch".
Fixed:
* Searches should now work correctly on Fossil Excavator (111).
> MT: Implemented 68-97, fixes on 111

- src/tcgwars/logic/impl/gen4/SecretWonders.groovy
- Roseanne's Research
- Night Maintenance
- Bebe's Search
> Various implementations

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen1/BaseSetNG.groovy
- src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
- src/tcgwars/logic/impl/gen3/Emerald.groovy
- src/tcgwars/logic/impl/gen3/UnseenForces.groovy
- src/tcgwars/logic/impl/gen4/HeartgoldSoulsilver.groovy
- src/tcgwars/logic/impl/gen7/BurningShadows.groovy
- src/tcgwars/logic/impl/gen7/CelestialStorm.groovy
- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
- src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy
- src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy
- src/tcgwars/logic/impl/gen7/GuardiansRising.groovy
- src/tcgwars/logic/impl/gen7/ShiningLegends.groovy
- src/tcgwars/logic/impl/gen7/SunMoon.groovy
- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
- src/tcgwars/logic/impl/gen7/TeamUp.groovy
- src/tcgwars/logic/impl/gen7/UltraPrism.groovy
- src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy
- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
- src/tcgwars/logic/impl/gen8/RebelClash.groovy
- src/tcgwars/logic/impl/gen8/SwordShield.groovy
- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
Reverts axpendix/tcgone-engine-contrib#559
> Revert "Opp's Active Energy Discard OoO fix, ADP extra prize order fix"

- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
Trying to use `targeted()` this time.
> Trev/Dusk GX SM217 - Fix Attempt 2

- src/tcgwars/logic/card/Collection.java
After adding the entry to the collections file, we'll be able to test out the Sword & Shield Promos on the dev server
> Add SWSHP to Collections file

- src/tcgwars/logic/groovy/TcgStatics.groovy
This is related to #569 as Natu CEC 78 uses it. I'm making it a separate PR since it touches a file outside of CosmicEclipse.groovy
> Statics: Add descriptive text to assertion

- src/tcgwars/logic/groovy/TcgStatics.groovy
Its not like it needs it but it was bugging me the first time
> Optimized rockPaperScissors

- src/tcgwars/logic/impl/gen8/SwordShield.groovy
I screwed up the default parameters :(
> Fix galarian stunfisk

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Leaving this as a draft for comments and for me to finish later.
> Cosmic eclipse fixes

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
I'm guessing self isn't valid in this closure, but thisCard should be.
> Rosa CEC 204 - Use thisCard for keyStore

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
> Rosa CEC 204 - keyStore must have 3 arguments

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
This PR is to fix any issues I find while testing my CEC fixes. Comments on whether something will work as expected or not are appreciated.
> Cosmic Eclipse Fixes Fixes

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
> Sylveon CEC 155 - Use PLAY_TRAINER instead

- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
Global Abilities don't have a self
> Sylveon CEC 155 - Use thisCard instead of self

- src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
- src/tcgwars/logic/impl/gen4/Platinum.groovy
- src/tcgwars/logic/impl/gen4/RisingRivals.groovy
- src/tcgwars/logic/impl/gen4/Stormfront.groovy
Implemented:
- Snowpoint Temple
- Azelf Lv.X
- Mesprit Lv.X
- Regigigas Lv.X
- Dialga G
- Dialga G Lv.X
> Implementations

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
- src/tcgwars/logic/impl/pokemod/PokemodBaseSet2.groovy
Electrode_21 implementation
Venomoth fixed to not crash on ability use
> Pokemod fixs

- src/tcgwars/logic/impl/gen4/HeartgoldSoulsilver.groovy
A first test, of possibly several.
> Rainbow Energy HGSS 104 - Try to correct image

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
> Roselia LM fixed

- src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy
- src/tcgwars/logic/impl/gen3/Emerald.groovy
- src/tcgwars/logic/impl/gen8/SwordShield.groovy
Also a Memory Berry (CG) fix I already had lol
> EX Emerald Fixes

- src/tcgwars/logic/impl/gen4/HeartgoldSoulsilver.groovy
> Rainbow E HGSS 104 - Fix type while keeping icon

- src/tcgwars/logic/impl/gen4/HeartgoldSoulsilver.groovy
Turns out there is a specific override for this.
> Rainbow E HGSS 104 - Fix type image for real

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Last attempt at figuring out why this breaks on deck but not on discard...
> More debug on Excavator

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Should avoid the crash, that needs checking though. But this should do as an alternative...
> Make Fossil Excavator (MT 111) filter before searching

- src/tcgwars/logic/impl/gen3/NintendoBlackStarPromos.groovy
- src/tcgwars/logic/impl/gen3/PopSeries1.groovy
- src/tcgwars/logic/impl/gen3/PopSeries2.groovy
- src/tcgwars/logic/impl/gen3/PopSeries3.groovy
- src/tcgwars/logic/impl/gen3/PopSeries4.groovy
- src/tcgwars/logic/impl/gen3/PopSeries5.groovy
This PR adds more sets to the existing Gen3 sets
> Add Gen3 Pop Series and Nintendo Black Star Promos

- src/tcgwars/logic/impl/gen4/Platinum.groovy
> Fixed typing of trainers + addition to import list

- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
This seemed like an interesting TODO to tackle.
> CELEBI_SM224 - Implement Call for Greatness

- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
Tried a method more similar to Professor Oak's Setup as @ufodynasty suggested.
> CELEBI_SM224 - Allow selecting all 3 at once

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
- src/tcgwars/logic/impl/pokemod/PokemodBaseSet2.groovy
Leaving as a draft until zfgoku confirms pokemonPower -> pokePower & pokeBody changes.
> Pokemod changes

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Implement some of Darkness Ablaze starting from the top:
Parasect
Carnivine
Simisage
Karrablast
Rowlet
Decidueye
> Darkness Ablaze: 4, 5, 7, 8, 11, 13

- src/tcgwars/logic/impl/pokemod/PokemodBaseSet.groovy
Now using penultimate every time in my pr titles.
> Final energymons

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
> ROWL_11 DAB - Fix Sky Circus

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
> Darkness ablaze quick fixes n+1

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
This should get me a list of fields for the class represented by ef
> ROWL_11 DAB - Add information gathering

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Bounsweet
Steenee
Tsareena
Wimpod
Golisopod
> DAB - Remaining [G] Pokémon

- src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy
Energy Bomb now moves energy after damage has been done.
> Fixed Dark Electrode's Energy Bomb

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Information gathering was a bust. This should work in theory though.
> ROWL_11 DAB - Fix

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Testing getting move's owner while checking `ENERGY_COST_CALCULATOR` with Rowlet. The rest are bug fixes for implementations.
> Darkness ablaze quick fixes and a test

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
I'm going to regret the part where I test these if I keep doing more, but I'm too bored to not do anything.
> Darkness ablaze - Start [F] Pokémon

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
> DAB - Bow to our parenthesis overlords once and for all

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
> Darkness ablaze quick fixes

- src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy
> Attempt to fix Pyroar (FLI 19)

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Hopefully this works. If it does I'll also fix the Rebel Clash ones that should work this way too.
> DAB - Fix energy retaining type in discard

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Did I say F last time, I'm really bad at connecting R = Fire F = Fighting :laughing:
> Darkness ablaze - Rest of the [R] Pokémon

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Deck is implicit may, Discard must be explicit may
> CENT_VMAX_36 DAB - Okay, but REALLY, it's a choice

- src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
- src/tcgwars/logic/impl/gen3/Emerald.groovy
- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
- src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
- src/tcgwars/logic/impl/gen3/UnseenForces.groovy
Darkness Energy now applies extra damage before Weakness/Resistance
> Darkness Energy fix

- src/tcgwars/logic/impl/gen3/UnseenForces.groovy
> Meganium ex PokePower fix

- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
Silver Wind's effect now properly unregisters
> Fixed Dustox's Silver Wind attack

- src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
> Fixed Vaporeon ex's Fastwave

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Trying to see if this event fires for all attachments or not
> Add check attach energy requirement debug string

- src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy
- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Unneeded, but maybe one param at the start might fix it?
> Fix attempt at Pow! Hand Extension (TRR) and Alakazam (MT)

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
See if this actually works for detailed debugging, just the object doesn't say much...
> Testing with dump() on Alakazam (MT)

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
> Final debug attempt for Alakazam (MT)

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
Bronzong should be easier than blissey. And added more specific messages for tracing interaction order.
> Remove most debug prints, changed debug target to bronzong

- src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy
- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
- src/tcgwars/logic/impl/gen3/Emerald.groovy
- src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy
- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
- src/tcgwars/logic/impl/gen3/UnseenForces.groovy
- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
- src/tcgwars/logic/impl/gen4/SecretWonders.groovy
Breaks the engine and doesn't permit the other testing to be done. Returns null anyways so rip this.
> Fix Umbreon ex, remove ef debug from Alakazam MT

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
This seems dumb, but it might just be dumb enough to work.
> SUIC_39 DAB - One last dumb test for the night

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
When you realize you're probably being dumb and can fix your mess to something far less mess.
> SUIC_39 DAB - Fix and simplify Aurora Loop

- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
With some help from flagrama c:
> Fix CARRACOSTA_GX_SM239 and add AIPOM_SM244

- src/tcgwars/logic/impl/gen3/PopSeries1.groovy
- src/tcgwars/logic/impl/gen3/PopSeries2.groovy
- src/tcgwars/logic/impl/gen3/PopSeries3.groovy
- src/tcgwars/logic/impl/gen3/PopSeries4.groovy
- src/tcgwars/logic/impl/gen3/PopSeries5.groovy
This PR adds the implementations for POP series 1-5, which is needed for the 2006 and 2007 formats.
> Add Implementation for POP Sets 1-5

- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
I think this should fix Carracosta GX's ability and Aipom's Yank Out attack.
> Fix CARRACOSTA_GX_SM239 and AIPOM_SM244

- src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy
- src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
- src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy
- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
- src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
- src/tcgwars/logic/impl/gen3/UnseenForces.groovy
- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
- src/tcgwars/logic/impl/gen7/GuardiansRising.groovy
- src/tcgwars/logic/impl/gen7/UnifiedMinds.groovy
- src/tcgwars/logic/impl/gen8/RebelClash.groovy
~~def didn't just copy that last card's name from the groovy file~~
> Fixed Bench-Reducing effect cards (Giant Stump, Road Block, Bellelba & Brycen-Man) not restoring abilities, plus some simplifications

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
- src/tcgwars/logic/impl/gen8/RebelClash.groovy
This should have every test case working, next would be the big mass-replace.
> More assert static fixes

- src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy
> Fix Rocket's Mission tags

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen3/CrystalGuardians.groovy
- src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
- src/tcgwars/logic/impl/gen4/DiamondPearlPromos.groovy
- src/tcgwars/logic/impl/gen4/SupremeVictors.groovy
- src/tcgwars/logic/impl/gen7/CosmicEclipse.groovy
No longer needed for now, but it improves #785 slightly.
> Fix Dual Ball, Remove debug code, fix old Drag Off attacks

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
Credits to ufo for the suggestion!
> New Level-Up implementation based on Holon's Pokémon

- src/tcgwars/logic/impl/gen7/HiddenFates.groovy
GXs with GX attacks that just do damage? What a boring set :laughing:
> Hidden Fates Fixes

- src/tcgwars/logic/impl/gen3/UnseenForces.groovy
Testing if it's a wrong param load...
> Fix choose maybe?

- src/tcgwars/logic/impl/gen3/UnseenForces.groovy
tfw noticed the problem on the line below but not here lol
> Fix something again but this time where everything breaks

- src/tcgwars/logic/impl/gen3/UnseenForces.groovy
The goal of this commit is to increase clarity of which energy you are discarding when you have multiple of the same multi energy attached. Can't request review of starg directly but will ask via discord
> multi energy 2/n is only selectable after multi energy 1/n has been selected

- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
Some checks are no longer needed, and refactored a flag.
> Improvements on Imprison

- src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy
The deck is now shuffled after the player gets an evolution card.
> Surprise! Time Machine fix

- src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
Will this be compatible with the implementation of Holon's Pokemon?
> Delta Switch only activates when player has Basic Energy in play

- src/tcgwars/logic/impl/gen8/SwordShield.groovy
Scans have already been uploaded. This should be good to merge immediately
> Add Sword & Shield Energy

- src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy
This will remove the extra period in the name that shows up when playing the card
> Remove period in ROCKET_S_ADMIN__86

- src/tcgwars/logic/impl/gen3/DragonFrontiers.groovy
- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
- src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
The Missing weakness is already pushed as a PR in carddb, as a note.
> "EX Power Keepers" Fixes

- src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy
- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
- src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy
- src/tcgwars/logic/impl/gen7/GuardiansRising.groovy
- src/tcgwars/logic/impl/gen7/UltraPrism.groovy
- src/tcgwars/logic/impl/gen7/UnbrokenBonds.groovy
Initially was meant to fix Ultra Recon Squad, but a couple other cards could also use some requirements.
> Add some Trainer card's requirements

- src/tcgwars/logic/groovy/TcgStatics.groovy
Used for a fix in Croagunk (Steam Siege 58).
> Added increasePoison() static

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Many small fixes. Almost all very minor. Also made sure you can't play Pokemon Breeder's Nurturing without a Pokemon that can evolve in play.
> Darkness ablaze fixes

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
> Handle Scoop Up and Devolution according to JP Q&A

- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
This is similar in spirit to #903 but with some additional changes to address some of the issues @flagrama encountered during testing.
There are now benchTrigger checks that occur `DEVOLVE` and `EVOLVE`.  
<sub><sup>Thank you for the help flagrama with Git... but I'm ashamed to say I've lost the battle against the git merge conflicts</sup></sub>
> Implement Eternatus VMAX

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
- src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy
- src/tcgwars/logic/impl/gen7/GuardiansRising.groovy
- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
- src/tcgwars/logic/impl/gen7/TeamUp.groovy
- src/tcgwars/logic/impl/gen8/DarknessAblaze.groovy
Mostly fixes to fixes from #928, plus a couple extra ones.
> More Fixes

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen3/DeltaSpecies.groovy
- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
- src/tcgwars/logic/impl/gen3/UnseenForces.groovy
- src/tcgwars/logic/impl/gen4/CallOfLegends.groovy
- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
- src/tcgwars/logic/impl/gen4/DiamondPearlPromos.groovy
- src/tcgwars/logic/impl/gen4/HeartgoldSoulsilver.groovy
- src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
- src/tcgwars/logic/impl/gen4/MajesticDawn.groovy
- src/tcgwars/logic/impl/gen4/Platinum.groovy
- src/tcgwars/logic/impl/gen4/RisingRivals.groovy
- src/tcgwars/logic/impl/gen4/Stormfront.groovy
- src/tcgwars/logic/impl/gen4/SupremeVictors.groovy
- src/tcgwars/logic/impl/gen4/Triumphant.groovy
- src/tcgwars/logic/impl/gen4/Undaunted.groovy
- src/tcgwars/logic/impl/gen7/GuardiansRising.groovy
- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
Even some Gen4 stuff because I'm sick of this refactor and never want to have to look at scoop up again :laughing:
> Even more scoop up

- src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
- src/tcgwars/logic/impl/gen4/Stormfront.groovy
- src/tcgwars/logic/impl/gen4/Triumphant.groovy
> Fix scoops

- src/tcgwars/logic/impl/gen1/BaseSetNG.groovy
- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
> Implement Pluspower (Base Set) in groovy

- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
- src/tcgwars/logic/impl/gen4/RisingRivals.groovy
- src/tcgwars/logic/impl/gen4/Stormfront.groovy
This PR will change the remaining `evolution` classes that are actually of `LVL_X` type into the `levelUp` class.
> Convert Remaining Evolutions to LevelUp

- src/tcgwars/logic/impl/gen3/Emerald.groovy
- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
- src/tcgwars/logic/impl/gen7/GuardiansRising.groovy
- src/tcgwars/logic/impl/gen7/HiddenFates.groovy
- src/tcgwars/logic/impl/gen7/TeamUp.groovy
toString method was added by @flagrama so this is no longer needed.
> thisAbility.name -> thisAbility

- src/tcgwars/logic/impl/gen2/AquapolisNG.groovy
- src/tcgwars/logic/impl/gen2/ExpeditionNG.groovy
- src/tcgwars/logic/impl/gen2/SkyridgeNG.groovy
- src/tcgwars/logic/impl/gen3/DragonNG.groovy
- src/tcgwars/logic/impl/gen3/HiddenLegendsNG.groovy
- src/tcgwars/logic/impl/gen3/RubySapphireNG.groovy
- src/tcgwars/logic/impl/gen3/SandstormNG.groovy
- src/tcgwars/logic/impl/gen3/TeamMagmaVsTeamAquaNG.groovy
- src/tcgwars/logic/impl/pokemod/PokemodAquapolis.groovy
- src/tcgwars/logic/impl/pokemod/PokemodExpedition.groovy
- src/tcgwars/logic/impl/pokemod/PokemodImperium.groovy
- src/tcgwars/logic/impl/pokemod/PokemodNeoDestiny.groovy
- src/tcgwars/logic/impl/pokemod/PokemodNeoGenesis.groovy
- src/tcgwars/logic/impl/pokemod/PokemodNeoRevelation.groovy
- src/tcgwars/logic/impl/pokemod/PokemodSkyridge.groovy
This PR will add the Groovy files for the following sets:
> Add NG sets + Pokemod Groovy files

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen3/FireRedLeafGreen.groovy
- src/tcgwars/logic/impl/gen7/CelestialStorm.groovy
- src/tcgwars/logic/impl/gen8/ChampionsPath.groovy
- src/tcgwars/logic/impl/gen8/SwordShieldPromos.groovy
One for selecting any number of energies from your Pokemon in play
One for doing additional damage for each energy discarded using the first method
I made them separately because the Galarian Sirfetch'd V's ability can use the first one as well (with some slight additional modification).
Are there any other cards that would use these, or could use these with additional modifications?
> Make two new statics and implement Galarian Sirfetch'd V promo

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen4/Triumphant.groovy
This should handle knockouts and changed implementations more cleanly.
> Fix the scoops some more because the nightmare never ends

- src/tcgwars/logic/card/Collection.java
> Change Abbreviation for FireRedLeafGreen

- src/tcgwars/logic/impl/gen8/LegendaryHeartbeat.groovy
This PR introduces the Groovy file for the Japanese set `Legendary Heartbeat`.
This will never be used in prod directly but it will help speed up development.
> Initial Legendary Heartbeat Groovy Template

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
- src/tcgwars/logic/impl/gen3/LegendMaker.groovy
- src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
- src/tcgwars/logic/impl/gen3/UnseenForces.groovy
- src/tcgwars/logic/impl/gen7/CelestialStorm.groovy
- src/tcgwars/logic/impl/gen7/GuardiansRising.groovy
- src/tcgwars/logic/impl/gen7/UltraPrism.groovy
This PR hopes to fix some of the issues regarding single letter variables.  I've replaced them with longer names and with more meaning, hopefully making it easier to read.
> Change Single Letter Variables

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen8/SwordShieldPromos.groovy
Depends on https://github.com/axpendix/tcgone/pull/96
> Use EnergySwitch with suppressLog to fix the issue without spamming the game log

- src/tcgwars/logic/impl/gen8/RebelClash.groovy
Clarify code, show cards to both players, discard after knockout
> Fix Cursed Shovel

- src/tcgwars/logic/impl/gen8/VividVoltage.groovy
This PR introduces the Groovy file for the upcoming set `Vivid Voltage`.
> Add Vivid Voltage Groovy Template

- src/tcgwars/logic/card/Collection.java
- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen8/LegendaryHeartbeat.groovy
Only the Beedrill line so far, but figure it best to put my progress up as I complete it. Probably easier to review each commit as it comes.
> Implement Legendary Heartbeat

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen8/AmazingVoltTackle.groovy
As with the Metronome static, I created one for Armor abilities since they are pretty common, and will use a separate future PR to implement it in all the appropriate places.
> Implement [W] Amazing Volt Tackle Pokemon and add static for "Armor" abilities

- src/tcgwars/logic/impl/gen8/AmazingVoltTackle.groovy
Shiftry's ability is a bit complicated. Skipping for the moment.
Also going to try breaking this set down more than Legendary Heartbeat, hoping to get it reviewed quicker.
> Amazing volt tackle [G]

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen8/LegendaryHeartbeat.groovy
Should resolve all of the issues the testers have found.
> Legendary heartbeat fixes

- src/tcgwars/logic/impl/gen8/SwordShieldPromos.groovy
- Remaining Champions Path Pin Collection Promos
- VIV Prerelease Promos
- VIV Blister Pack Promos
> VIV Release Day Promos

- src/tcgwars/logic/impl/gen8/AmazingVoltTackle.groovy
- src/tcgwars/logic/impl/gen8/LegendaryHeartbeat.groovy
All attacks should have their English names and mention Energy types where appropriate.
> viv text corrections

- src/tcgwars/logic/impl/gen4/Stormfront.groovy
- src/tcgwars/logic/util/PokemonCardSet.java
This PR is tied to https://github.com/axpendix/tcgone/pull/82 and https://github.com/axpendix/tcgone/pull/108
But also includes some changes to correct the class of some of the Lv.X cards from `evolution` to `levelUp`.
> Update Deckbuilder to Accomodate Lv.X Limit

- src/tcgwars/logic/impl/gen7/TeamUp.groovy
This has been bugging me for a while.
> Jirachi tweak to reduce clicks

- src/tcgwars/logic/impl/gen4/Triumphant.groovy
Still need to figure out how to write absol. I don't know how to access the played pokemon within an after PLAY_BASIC_POKEMON
> Triumphant

- src/tcgwars/logic/impl/gen4/CallOfLegends.groovy
Will commit to this as more bugs are found.
> Call Of Legends Fixes

- src/tcgwars/logic/impl/gen4/SecretWonders.groovy
Implements SW 1-6. Pushing early to test gallade implementation
> Initial Secret Wonders

- src/tcgwars/logic/impl/gen4/SecretWonders.groovy
Trying to avoid an npe but am not sure what caused it.
You can't use my or self on a pcs that has be knocked out by your opponent afaik.
> Electrode 26

- src/tcgwars/logic/impl/gen4/DiamondPearlPromos.groovy
- src/tcgwars/logic/impl/gen4/GreatEncounters.groovy
- src/tcgwars/logic/impl/gen4/Stormfront.groovy
> Implement GreatEncounters

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/impl/gen4/MajesticDawn.groovy
We all know this is going to take a few tries. Ill merge this tomorrow when Im actually awake.
> Majestic Dawn (1/10)

- src/tcgwars/logic/impl/gen4/SecretWonders.groovy
Turns out the code I wanted was already a thing. I just needed to find it.
> Shuckle finishing touches

- src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
> Implement Legends Awakened

- src/tcgwars/logic/impl/gen8/ShiningFates.groovy
> Add Shining Fates Groovy Template

- src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
Should also remove the statuses when first put in play.
> Power Keepers: Sidney's Stadium (82): Fix onPlay

- src/tcgwars/logic/impl/gen8/ShiningFates.groovy
This PR the latest set Shining Fates which was released on 2/19/21.
> Implement Shining Fates Set

- src/tcgwars/logic/card/Collection.java
This will allow the set to be defined and testable on the dev server
> Add Shining Fates to Collections

- src/tcgwars/logic/impl/gen7/CelestialStorm.groovy
Ruling: https://compendium.pokegym.net/compendium-bw.html#601
Fixes https://forum.tcgone.net/t/bug-report-rayquaza-gri-106-venusaur-slg-3-the-gr/920
> CES109: Count the Energy, not the Cards

- src/tcgwars/logic/impl/pokemod/PokemodFossil.groovy
- src/tcgwars/logic/impl/pokemod/PokemodJungle.groovy
- src/tcgwars/logic/impl/pokemod/PokemodTeamRocket.groovy
- src/tcgwars/logic/impl/pokemod/PokemodWizardsBlackStarPromos.groovy
> Pokemod Fossil, Jungle, Black Star Promos

- src/tcgwars/logic/impl/gen7/SunMoonPromos.groovy
Fixes https://forum.tcgone.net/t/bug-report-shining-ho-oh-smp-70-ho-ohs-ability-lets/900
Also cleans up the interaction in general to be a bit more user-friendly.
> SM70: Owner should choose, not opponent

- src/tcgwars/logic/impl/gen7/CrimsonInvasion.groovy
Should fix https://forum.tcgone.net/t/bug-report-chimecho-cin-43-vikavolt-sm-52-i-used/2244 and related issues.
> CIN43: Handle Rare Candy interactions

- src/tcgwars/logic/impl/gen7/TeamUp.groovy
- src/tcgwars/logic/impl/gen8/BattleStyles.groovy
> Battle Style Fixes

- src/tcgwars/logic/impl/gen2/ExpeditionNG.groovy
Should fix https://forum.tcgone.net/t/bug-report-arcanine-skr-3-typhlosion-exp-28-scree/2495
> EXP29: Use a getter instead of modifying energies

- src/tcgwars/logic/groovy/TcgStatics.groovy
Used the wrong check for this.
> MetronomeA: Fix special conditions check

- src/tcgwars/logic/impl/gen7/GuardiansRising.groovy
Fixes https://forum.tcgone.net/t/bug-report-professor-elms-lecture-lot-213-alolan-ni/2741/2 more or less
> GRI60: Add showToOpponent to selection

- src/tcgwars/logic/impl/gen4/RisingRivals.groovy
> Fix pbg typo

- src/tcgwars/logic/impl/gen8/ShinyStarV.groovy
Fixes non-reported bug displayed in this game log https://forum.tcgone.net/t/br-victini-vmax-bst-22-there-is-a-problem-with-the-card-ment/11851
> SHF41: Fix failed deck search

- src/tcgwars/logic/impl/gen7/UltraPrism.groovy
Fixes https://forum.tcgone.net/t/bug-report-gardenia-upr-124-my-opponent-was-able-to-t/2752
> UPR124: Fix playRequirement

- src/tcgwars/logic/impl/gen4/Arceus.groovy
- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
- src/tcgwars/logic/impl/gen4/GreatEncounters.groovy
- src/tcgwars/logic/impl/gen4/HeartgoldSoulsilver.groovy
- src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
- src/tcgwars/logic/impl/gen4/MajesticDawn.groovy
- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
- src/tcgwars/logic/impl/gen4/Platinum.groovy
- src/tcgwars/logic/impl/gen4/RisingRivals.groovy
- src/tcgwars/logic/impl/gen4/SecretWonders.groovy
- src/tcgwars/logic/impl/gen4/Stormfront.groovy
- src/tcgwars/logic/impl/gen4/SupremeVictors.groovy
- src/tcgwars/logic/impl/gen4/Triumphant.groovy
- src/tcgwars/logic/impl/gen4/Undaunted.groovy
- src/tcgwars/logic/impl/gen4/Unleashed.groovy
> Rising rivals code review fixes

- src/tcgwars/logic/impl/gen4/Stormfront.groovy
Doesn't really handle interactions based on rulings currently. Does generally work though. `after KNOCKOUT` may actually be the correct place to handle the Stadium implementation change? Needs testing though.
> Implement Dusknoir Lv.X

- src/tcgwars/logic/impl/gen4/Arceus.groovy
- src/tcgwars/logic/impl/gen4/DiamondPearl.groovy
- src/tcgwars/logic/impl/gen4/GreatEncounters.groovy
- src/tcgwars/logic/impl/gen4/HeartgoldSoulsilver.groovy
- src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
- src/tcgwars/logic/impl/gen4/MajesticDawn.groovy
- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
- src/tcgwars/logic/impl/gen4/Platinum.groovy
- src/tcgwars/logic/impl/gen4/RisingRivals.groovy
- src/tcgwars/logic/impl/gen4/SecretWonders.groovy
- src/tcgwars/logic/impl/gen4/Stormfront.groovy
- src/tcgwars/logic/impl/gen4/SupremeVictors.groovy
- src/tcgwars/logic/impl/gen4/Triumphant.groovy
- src/tcgwars/logic/impl/gen4/Undaunted.groovy
- src/tcgwars/logic/impl/gen4/Unleashed.groovy
Fixes all bugs found in stormfront on trello.
> Stormfront + sources

- src/tcgwars/logic/impl/gen4/PopSeries7.groovy
All the cards were reprints so only linking was needed
> Update Pop Series 7 Set

- src/tcgwars/logic/impl/gen4/PokemonRumble.groovy
Doing some tiding up for the Pokemon Rumble promo set
> Update Pokemon Rumble

- src/tcgwars/logic/impl/gen4/PopSeries9.groovy
Initial run through of the set
> Implement Pop Series 9

- src/tcgwars/logic/impl/gen4/PopSeries8.groovy
> Implement Pop Series 8

- src/tcgwars/logic/impl/gen4/PopSeries6.groovy
Initial run through of the Pop Series 6 set
> Implement Pop Series 6

- src/tcgwars/logic/impl/gen4/HeartgoldSoulsilverPromos.groovy
> Implement HeartGold SoulSilver Promos

- src/tcgwars/logic/impl/gen4/DiamondPearlPromos.groovy
First initial run through for implementing the DPP set
> Implement Diamond and Pearl Promos

- src/tcgwars/logic/impl/gen4/Platinum.groovy
Fix crash on Chemical Scale attack
> Fix Platinum Dustox_25

- src/tcgwars/logic/impl/gen4/Platinum.groovy
Various Fixes to the Gen4 Platinum set
There will probably be a second PR after this for the Platinum set
> Platinum Set Fixes

- src/tcgwars/logic/impl/gen7/ForbiddenLight.groovy
- src/tcgwars/logic/impl/gen8/BattleStyles.groovy
A bit more complicated than similar effects since it only affects one target instead of the whole battleground, but I think this should work.
> Implement Tool Jammer

- src/tcgwars/logic/impl/gen4/Stormfront.groovy
Energies should no longer attempt to be attached to a KO'ed self.
> Fixed SF Regigigas Lv X 100

- src/tcgwars/logic/impl/gen8/BattleStyles.groovy
Affect the opponent's current active Pokémon instead of stale values
> Fix Tool Jammer

- src/tcgwars/logic/impl/gen8/BattleStyles.groovy
playerType is not a param value.
> Fix BST Kingdra

- src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy
> Dark houndoom should be able to discard special energy.

- src/tcgwars/logic/impl/gen3/PowerKeepers.groovy
> Fix an infinite loop with Blaziken (PK)

- src/tcgwars/logic/impl/gen4/Arceus.groovy
- src/tcgwars/logic/impl/gen4/MajesticDawn.groovy
Going through the bugs from trello regarding gen4 Arceus cards
> Arceus Set Bugfixes

- src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
Addressing issues regarding the Gen4 Legends Awakened set bugs found on trello
> Legends Awakened Bugfixes

- src/tcgwars/logic/impl/gen8/ChillingReign.groovy
Scraped from Pokebeach, here is the initial Groovy Template
> Initial Chilling Reign Template

- src/tcgwars/logic/impl/gen8/ChillingReign.groovy
Formatting for evolutions were incorrect
> Fix Chilling Reign Evolutions

- src/tcgwars/logic/impl/gen8/ChillingReign.groovy
First passthrough of Chilling Reign
> Initial Implementation of Chilling Reign

- src/tcgwars/logic/impl/gen8/ChillingReign.groovy
This PR has changes regarding the unaddressed comments made in #1279
> Chilling Reign Changes

- src/tcgwars/logic/impl/gen8/ChillingReign.groovy
> Fix Chilling Reign Bugs

- src/tcgwars/logic/impl/gen4/Undaunted.groovy
Fixes for the Gen4 set Undaunted on Trello
> Undaunted Set Fixes

- src/tcgwars/logic/impl/gen4/Platinum.groovy
Fix crash on Nurse call ability
> Fix Platinum Blissey_22

- src/tcgwars/logic/impl/pokemod/PokemodTeamRocket.groovy
not even close to done
does this work now
> Pokemod rocket stuff2

- src/tcgwars/logic/impl/pokemod/PokemodFossil.groovy
Adding in some secret rare cards and fixing bugs
> Updateing PokemodFossil.groovy

- src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
patches unresolved issues in previous pr.
> LA 1-27, 48-51 patches

- src/tcgwars/logic/impl/gen4/Platinum.groovy
Add sleep to Midnight Eyes and fix Perish Song crash
> Platinum fix Altaria_18

- src/tcgwars/logic/card/Collection.java
- src/tcgwars/logic/impl/gen8/BlueSkyStream.groovy
- src/tcgwars/logic/impl/gen8/EeveeHeroes.groovy
- src/tcgwars/logic/impl/gen8/SkyscrapingPerfection.groovy
This PR adds the groovy files for the Japanese sets that make up the English Evolving Skies
> Add Evolving Skies Japanese Sets

- src/tcgwars/logic/impl/gen4/MysteriousTreasures.groovy
changing evloves from for quilava so cyndaquil is seen as a valid target
> fixing quilava

- src/tcgwars/logic/impl/gen4/MajesticDawn.groovy
changes the F to R so that the cost correctly matches the card image
> chimchar md56 fix

- src/tcgwars/logic/card/Collection.java
- src/tcgwars/logic/impl/gen8/EeveeHeroesVmaxSpecialSet.groovy
Contains 4 eeveelution vmax forms
> Add Special Set Eevee Heroes VMAX 

- src/tcgwars/logic/impl/gen8/BlueSkyStream.groovy
Depends on https://github.com/axpendix/tcgone/pull/186
> Implement Blue Sky Stream Grass

- src/tcgwars/logic/impl/gen8/EeveeHeroesVmaxSpecialSet.groovy
adding in the eevee heroes vmax special set cards
> eevee heroes vmax special set

- src/tcgwars/logic/impl/gen8/BlueSkyStream.groovy
Cards still needing implemented:
* RUBBERY_GLOVES_60
* NETHER_MASK_61
* RAPID_STRIKE_SCROLL_OF_THE_FLYING_DRAGON_62
* ZINNIA_S_RESOLVE_65
* STORMY_MOUNTAIN_RANGE_66
> Implement most of the remaining cards for BlueSkyStream

- src/tcgwars/logic/impl/gen8/SkyscrapingPerfection.groovy
- src/tcgwars/logic/util/DeckCardList.groovy
Trainers still need done.
@axpendix Tried to add auto deck shuffling any time the deck is searched and seems to work. Would appreciate you take a look to make sure it doesn't seem like it will break anything.
> Automatically shuffle deck on search & Pokémon of Towering Perfection

- src/tcgwars/logic/card/Collection.java
- src/tcgwars/logic/impl/gen1/IntroPack.Groovy
Added the cards from the Intro Pack. While this is a japanese only half deck, it does contain some cards that only appear in the pack. Those cards do not have Rarity Symbols, thus the symbols provided by Pokemon TCG GB2 have been used.
> Intro Pack Cards

- src/tcgwars/logic/groovy/TcgStatics.groovy
- src/tcgwars/logic/util/CardList.groovy
- src/tcgwars/logic/util/DeckCardList.groovy
- src/tcgwars/logic/util/PcsList.groovy
This fixes the build process after the refactors made in https://github.com/axpendix/tcgone/commit/a551752e545af93d320a3bf047dca816ea7e61e3.
> Add missing imports from the request builders refactor

- src/tcgwars/logic/impl/gen1/BaseSetNG.groovy
Fixes: https://forum.tcgone.net/t/br-alakazam-bs-1-alakazam-is-not-able-to-use-his-ability-whe/12729
> Fix Base Set legacy special condition check

- src/tcgwars/logic/impl/gen4/RisingRivals.groovy
> Empty commit, test CI

- src/tcgwars/logic/impl/gen3/AurasLucario.groovy
- src/tcgwars/logic/impl/gen3/PopSeries3.groovy
Adding a new JP set. (Plus small bug fix for Vaporeon POP3.)
> Aura's Lucario

- src/tcgwars/logic/impl/gen3/DragonNG.groovy
> Move MUK_EX to groovy where the interaction _just works_

- src/tcgwars/logic/impl/gen8/ShinyStarV.groovy
Would only fail if the last card tested was invalid. Now tests that every card passes the passFilter.
> Fix Ball Guy's passFilter

- src/tcgwars/logic/impl/gen3/HolonPhantoms.groovy
- src/tcgwars/logic/impl/gen3/PopSeries1.groovy
- src/tcgwars/logic/impl/gen3/TeamRocketReturns.groovy
- src/tcgwars/logic/impl/gen4/Arceus.groovy
- src/tcgwars/logic/impl/gen4/LegendsAwakened.groovy
- src/tcgwars/logic/impl/gen4/MajesticDawn.groovy
Caught a Game Engine Error in dev, caused by using `pcs` before defining it.
edit: also quickly fixed Giratina LA which Tegull found
> Cradily LA fix

- src/tcgwars/logic/impl/gen8/Celebrations.groovy
Hey I am interested in contributing to the project and implement the attacks and abilities for these cards that are not yet added to TCGOne. I would like to test if this ability works as I intended and would appreciate your feedback on how best to do this testing on my end locally before issuing a pull request. 
This PR is to add the Mysterious Tail ability for MEW_11 in the Celebrations set (the set after Evolving skies which is the latest updated set in TCGOne).
> Add Ability MEW_11 Mysterious Tail
